# Generated by Django 5.0.8 on 2024-08-28 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0002_authorsorderable"),
        ("exhibits", "0013_alter_exhibitpage_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authorsorderable",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="authorsorderable",
            unique_together={("page", "author")},
        ),
    ]
