# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qwak/features_operator/v3/features_operator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1qwak/features_operator/v3/features_operator.proto\x12\x19qwak.features_operator.v3\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8c\x02\n\x19ValidationSuccessResponse\x12\x0e\n\x06sample\x18\x01 \x01(\t\x12U\n\x19pandas_column_description\x18\x02 \x03(\x0b\x32\x32.qwak.features_operator.v3.PandasColumnDescription\x12S\n\x18spark_column_description\x18\x03 \x03(\x0b\x32\x31.qwak.features_operator.v3.SparkColumnDescription\x12\x33\n\x07outputs\x18\x04 \x01(\x0b\x32\".qwak.features_operator.v3.Outputs\"C\n\x17PandasColumnDescription\x12\x13\n\x0b\x63olumn_name\x18\x01 \x01(\t\x12\x13\n\x0bpandas_type\x18\x02 \x01(\t\"A\n\x16SparkColumnDescription\x12\x13\n\x0b\x63olumn_name\x18\x01 \x01(\t\x12\x12\n\nspark_type\x18\x02 \x01(\t\"\x8b\x01\n\x19ValidationFailureResponse\x12\r\n\x05phase\x18\x01 \x01(\t\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x33\n\x07outputs\x18\x04 \x01(\x0b\x32\".qwak.features_operator.v3.Outputs\")\n\x07Outputs\x12\x0e\n\x06stdout\x18\x01 \x01(\t\x12\x0e\n\x06stderr\x18\x02 \x01(\t\"\x1c\n\x1aValidationNotReadyResponseB(\n$com.qwak.ai.features.operator.api.v3P\x01\x62\x06proto3')



_VALIDATIONSUCCESSRESPONSE = DESCRIPTOR.message_types_by_name['ValidationSuccessResponse']
_PANDASCOLUMNDESCRIPTION = DESCRIPTOR.message_types_by_name['PandasColumnDescription']
_SPARKCOLUMNDESCRIPTION = DESCRIPTOR.message_types_by_name['SparkColumnDescription']
_VALIDATIONFAILURERESPONSE = DESCRIPTOR.message_types_by_name['ValidationFailureResponse']
_OUTPUTS = DESCRIPTOR.message_types_by_name['Outputs']
_VALIDATIONNOTREADYRESPONSE = DESCRIPTOR.message_types_by_name['ValidationNotReadyResponse']
ValidationSuccessResponse = _reflection.GeneratedProtocolMessageType('ValidationSuccessResponse', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATIONSUCCESSRESPONSE,
  '__module__' : 'qwak.features_operator.v3.features_operator_pb2'
  # @@protoc_insertion_point(class_scope:qwak.features_operator.v3.ValidationSuccessResponse)
  })
_sym_db.RegisterMessage(ValidationSuccessResponse)

PandasColumnDescription = _reflection.GeneratedProtocolMessageType('PandasColumnDescription', (_message.Message,), {
  'DESCRIPTOR' : _PANDASCOLUMNDESCRIPTION,
  '__module__' : 'qwak.features_operator.v3.features_operator_pb2'
  # @@protoc_insertion_point(class_scope:qwak.features_operator.v3.PandasColumnDescription)
  })
_sym_db.RegisterMessage(PandasColumnDescription)

SparkColumnDescription = _reflection.GeneratedProtocolMessageType('SparkColumnDescription', (_message.Message,), {
  'DESCRIPTOR' : _SPARKCOLUMNDESCRIPTION,
  '__module__' : 'qwak.features_operator.v3.features_operator_pb2'
  # @@protoc_insertion_point(class_scope:qwak.features_operator.v3.SparkColumnDescription)
  })
_sym_db.RegisterMessage(SparkColumnDescription)

ValidationFailureResponse = _reflection.GeneratedProtocolMessageType('ValidationFailureResponse', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATIONFAILURERESPONSE,
  '__module__' : 'qwak.features_operator.v3.features_operator_pb2'
  # @@protoc_insertion_point(class_scope:qwak.features_operator.v3.ValidationFailureResponse)
  })
_sym_db.RegisterMessage(ValidationFailureResponse)

Outputs = _reflection.GeneratedProtocolMessageType('Outputs', (_message.Message,), {
  'DESCRIPTOR' : _OUTPUTS,
  '__module__' : 'qwak.features_operator.v3.features_operator_pb2'
  # @@protoc_insertion_point(class_scope:qwak.features_operator.v3.Outputs)
  })
_sym_db.RegisterMessage(Outputs)

ValidationNotReadyResponse = _reflection.GeneratedProtocolMessageType('ValidationNotReadyResponse', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATIONNOTREADYRESPONSE,
  '__module__' : 'qwak.features_operator.v3.features_operator_pb2'
  # @@protoc_insertion_point(class_scope:qwak.features_operator.v3.ValidationNotReadyResponse)
  })
_sym_db.RegisterMessage(ValidationNotReadyResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n$com.qwak.ai.features.operator.api.v3P\001'
  _VALIDATIONSUCCESSRESPONSE._serialized_start=114
  _VALIDATIONSUCCESSRESPONSE._serialized_end=382
  _PANDASCOLUMNDESCRIPTION._serialized_start=384
  _PANDASCOLUMNDESCRIPTION._serialized_end=451
  _SPARKCOLUMNDESCRIPTION._serialized_start=453
  _SPARKCOLUMNDESCRIPTION._serialized_end=518
  _VALIDATIONFAILURERESPONSE._serialized_start=521
  _VALIDATIONFAILURERESPONSE._serialized_end=660
  _OUTPUTS._serialized_start=662
  _OUTPUTS._serialized_end=703
  _VALIDATIONNOTREADYRESPONSE._serialized_start=705
  _VALIDATIONNOTREADYRESPONSE._serialized_end=733
# @@protoc_insertion_point(module_scope)
