from enum import Enum

class MissionStatusEnum(Enum): 
    STATUS_UNKNOWN=0
    STATUS_ACCEPTED=1
    STATUS_EXECUTING=2
    STATUS_CANCELING=3
    STATUS_SUCCEEDED=4
    STATUS_CANCELED=5
    STATUS_ABORTED=6