# Generated by Django 5.1.7 on 2025-04-02 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_audit_log", "0003_alter_accesslog_data_alter_accesslog_ip_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesslog",
            name="user_agent",
            field=models.TextField(
                blank=True,
                editable=False,
                help_text="User Agent string (deprecated)",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="LogUserAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_agent", models.TextField(editable=False, unique=True)),
                (
                    "browser",
                    models.CharField(
                        blank=True, editable=False, max_length=50, null=True
                    ),
                ),
                (
                    "browser_version",
                    models.CharField(
                        blank=True, editable=False, max_length=20, null=True
                    ),
                ),
                (
                    "operating_system",
                    models.CharField(
                        blank=True, editable=False, max_length=50, null=True
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        blank=True, editable=False, max_length=20, null=True
                    ),
                ),
                ("is_bot", models.BooleanField(default=False, editable=False)),
            ],
            options={
                "verbose_name": "Log User Agent",
                "verbose_name_plural": "Log User Agents",
                "indexes": [
                    models.Index(
                        fields=["browser"], name="django_audi_browser_65f0aa_idx"
                    ),
                    models.Index(
                        fields=["operating_system"],
                        name="django_audi_operati_c5de1a_idx",
                    ),
                    models.Index(
                        fields=["device_type"], name="django_audi_device__424a4f_idx"
                    ),
                    models.Index(
                        fields=["is_bot"], name="django_audi_is_bot_967733_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="accesslog",
            name="user_agent_normalized",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Normalized user agent information",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="access_logs",
                to="django_audit_log.loguseragent",
            ),
        ),
    ]
