
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-06-25T12:40:07-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "5d8b944d79cf6574257fc7bb474f1b155d8192ed",
 "version": "0.2.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
