
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-06-25T16:00:57+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "bdd78329fa8ffec0f992d795466ecf0a56e5d41c",
 "version": "2.0.3a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
