import codecs
from setuptools import setup, find_packages

setup(
    name='fastaccesscontrol',
    version='0.0.1beta1',
    description="FastAccessControl Server is a high-performance, secure, pure-Python socket server & client for distributed rate limiting and IP access control to your API services — all in under 0.0001s (plus network latency).",
    url='https://github.com/rabuchaim/fastaccesscontrol',
    author='Ricardo Abuchaim',
    author_email='ricardoabuchaim@gmail.com',
    maintainer='Ricardo Abuchaim',
    maintainer_email='ricardoabuchaim@gmail.com',
    project_urls={
        "Issue Tracker": "https://github.com/rabuchaim/fastaccesscontrol/issues",
        "Source code": "https://github.com/rabuchaim/fastaccesscontrol"
    },
    bugtrack_url='https://github.com/rabuchaim/fastaccesscontrol/issues',
    license='MIT',
    keywords=[''],
    packages=find_packages(),
    py_modules=['fastaccesscontrol', 'fastaccesscontrol'],
    package_dir = {'fastaccesscontrol': 'fastaccesscontrol'},
    include_package_data=True,
    zip_safe = False,
    package_data={
        'fastaccesscontrol': [
            'README.md',
            '__init__.py',
            'fastaccesscontrol.py',
        ],
    },
    python_requires=">=3.10",
    install_requires=[],
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Topic :: Security',
        'Topic :: Internet',
        'Topic :: Internet :: Finger',
        'Topic :: Scientific/Engineering',
        'Topic :: System :: Monitoring',
        'Topic :: System :: Networking',
        'Topic :: System :: Systems Administration',
        'Topic :: Software Development :: Libraries',
        'Topic :: Software Development :: Libraries :: Python Modules',
        'Topic :: Software Development :: Localization',
        'Topic :: Utilities',
        'Intended Audience :: Developers',
        'Intended Audience :: Information Technology',
        'Intended Audience :: System Administrators',
        'Operating System :: MacOS',
        'Operating System :: Microsoft :: Windows :: Windows 10',
        'Operating System :: Microsoft :: Windows :: Windows 11',
        'Operating System :: Unix',
        'Operating System :: POSIX',
        'Operating System :: POSIX :: Linux',
        'Operating System :: POSIX :: BSD',
        'Operating System :: POSIX :: BSD :: FreeBSD',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3.10',  
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3.12',
        'Programming Language :: Python :: 3.13',
        'Programming Language :: Python :: Implementation :: PyPy',
        'License :: OSI Approved :: MIT License',
    ],
    long_description=codecs.open("README.md","r","utf-8").read(),
    long_description_content_type='text/markdown',
)
