# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cambai.models.request_dubbed_output_in_alt_format200_response import RequestDubbedOutputInAltFormat200Response

class TestRequestDubbedOutputInAltFormat200Response(unittest.TestCase):
    """RequestDubbedOutputInAltFormat200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestDubbedOutputInAltFormat200Response:
        """Test RequestDubbedOutputInAltFormat200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestDubbedOutputInAltFormat200Response`
        """
        model = RequestDubbedOutputInAltFormat200Response()
        if include_optional:
            return RequestDubbedOutputInAltFormat200Response(
                output_url = None,
                task_id = ''
            )
        else:
            return RequestDubbedOutputInAltFormat200Response(
        )
        """

    def testRequestDubbedOutputInAltFormat200Response(self):
        """Test RequestDubbedOutputInAltFormat200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
