# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cambai.models.audio_separation_run_info_response import AudioSeparationRunInfoResponse

class TestAudioSeparationRunInfoResponse(unittest.TestCase):
    """AudioSeparationRunInfoResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AudioSeparationRunInfoResponse:
        """Test AudioSeparationRunInfoResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AudioSeparationRunInfoResponse`
        """
        model = AudioSeparationRunInfoResponse()
        if include_optional:
            return AudioSeparationRunInfoResponse(
                foreground_audio_url = '',
                background_audio_url = ''
            )
        else:
            return AudioSeparationRunInfoResponse(
        )
        """

    def testAudioSeparationRunInfoResponse(self):
        """Test AudioSeparationRunInfoResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
