"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import grpc
import luminarycloud._proto.api.v0.luminarycloud.thirdpartyintegration.onshape.onshape_pb2

class OnshapeServiceStub:
    """Public API service for Onshape third-party integration functionality.
    Exposes authentication status checking and variable fetching capabilities.
    """

    def __init__(self, channel: grpc.Channel) -> None: ...
    GetAuthenticationStatus: grpc.UnaryUnaryMultiCallable[
        luminarycloud._proto.api.v0.luminarycloud.thirdpartyintegration.onshape.onshape_pb2.GetAuthenticationStatusRequest,
        luminarycloud._proto.api.v0.luminarycloud.thirdpartyintegration.onshape.onshape_pb2.GetAuthenticationStatusReply,
    ]
    """Checks whether the current user has valid authentication with Onshape."""
    FetchVariables: grpc.UnaryUnaryMultiCallable[
        luminarycloud._proto.api.v0.luminarycloud.thirdpartyintegration.onshape.onshape_pb2.FetchVariablesRequest,
        luminarycloud._proto.api.v0.luminarycloud.thirdpartyintegration.onshape.onshape_pb2.FetchVariablesReply,
    ]
    """Fetches the list of variable names available in the specified Onshape element."""

class OnshapeServiceServicer(metaclass=abc.ABCMeta):
    """Public API service for Onshape third-party integration functionality.
    Exposes authentication status checking and variable fetching capabilities.
    """

    @abc.abstractmethod
    def GetAuthenticationStatus(
        self,
        request: luminarycloud._proto.api.v0.luminarycloud.thirdpartyintegration.onshape.onshape_pb2.GetAuthenticationStatusRequest,
        context: grpc.ServicerContext,
    ) -> luminarycloud._proto.api.v0.luminarycloud.thirdpartyintegration.onshape.onshape_pb2.GetAuthenticationStatusReply:
        """Checks whether the current user has valid authentication with Onshape."""
    @abc.abstractmethod
    def FetchVariables(
        self,
        request: luminarycloud._proto.api.v0.luminarycloud.thirdpartyintegration.onshape.onshape_pb2.FetchVariablesRequest,
        context: grpc.ServicerContext,
    ) -> luminarycloud._proto.api.v0.luminarycloud.thirdpartyintegration.onshape.onshape_pb2.FetchVariablesReply:
        """Fetches the list of variable names available in the specified Onshape element."""

def add_OnshapeServiceServicer_to_server(servicer: OnshapeServiceServicer, server: grpc.Server) -> None: ...
