# Generated by Django 5.0.8 on 2024-08-26 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nhanes", "0002_alter_cycle_options_alter_data_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="variablecycle",
            unique_together={("version", "variable", "cycle", "dataset")},
        ),
    ]
