# coding: utf-8

"""
    AristaFlowREST/OrgModelManager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 5.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AndStringFilter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '_and': 'list[StringFilter]'
    }

    attribute_map = {
        '_and': 'and'
    }

    def __init__(self, _and=None):  # noqa: E501
        """AndStringFilter - a model defined in Swagger"""  # noqa: E501
        self.__and = None
        if not(hasattr(self, "discriminator")) or not(self.discriminator):
            self.discriminator = None
        self._and = _and

    @property
    def _and(self):
        """Gets the _and of this AndStringFilter.  # noqa: E501


        :return: The _and of this AndStringFilter.  # noqa: E501
        :rtype: list[StringFilter]
        """
        return self.__and

    @_and.setter
    def _and(self, _and):
        """Sets the _and of this AndStringFilter.


        :param _and: The _and of this AndStringFilter.  # noqa: E501
        :type: list[StringFilter]
        """
        if _and is None:
            raise ValueError("Invalid value for `_and`, must not be `None`")  # noqa: E501

        self.__and = _and

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AndStringFilter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AndStringFilter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
