# coding: utf-8

"""
    AristaFlowREST/OrgModelManager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 5.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ModelChangeOperationsPasswordqualityBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'password': 'str',
        'blacklist': 'list[str]'
    }

    attribute_map = {
        'password': 'password',
        'blacklist': 'blacklist'
    }

    def __init__(self, password=None, blacklist=None):  # noqa: E501
        """ModelChangeOperationsPasswordqualityBody - a model defined in Swagger"""  # noqa: E501
        self._password = None
        self._blacklist = None
        if not(hasattr(self, "discriminator")) or not(self.discriminator):
            self.discriminator = None
        self.password = password
        if blacklist is not None:
            self.blacklist = blacklist

    @property
    def password(self):
        """Gets the password of this ModelChangeOperationsPasswordqualityBody.  # noqa: E501


        :return: The password of this ModelChangeOperationsPasswordqualityBody.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this ModelChangeOperationsPasswordqualityBody.


        :param password: The password of this ModelChangeOperationsPasswordqualityBody.  # noqa: E501
        :type: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    @property
    def blacklist(self):
        """Gets the blacklist of this ModelChangeOperationsPasswordqualityBody.  # noqa: E501


        :return: The blacklist of this ModelChangeOperationsPasswordqualityBody.  # noqa: E501
        :rtype: list[str]
        """
        return self._blacklist

    @blacklist.setter
    def blacklist(self, blacklist):
        """Sets the blacklist of this ModelChangeOperationsPasswordqualityBody.


        :param blacklist: The blacklist of this ModelChangeOperationsPasswordqualityBody.  # noqa: E501
        :type: list[str]
        """

        self._blacklist = blacklist

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ModelChangeOperationsPasswordqualityBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ModelChangeOperationsPasswordqualityBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
