from setuptools import setup, find_packages

setup(
    name="PyPeUrlLoader",
    version="1.0.0",
    py_modules=["PyPeUrlLoader"],
    packages=find_packages(include=[]),
    install_requires=["PyPeLoader"],
    scripts=[],
    author="Maurice Lambert",
    author_email="mauricelambert434@gmail.com",
    maintainer="Maurice Lambert",
    maintainer_email="mauricelambert434@gmail.com",
    description="This package uses PyPeLoader to load a PE program from a HTTP server (from an URL).",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/mauricelambert/PyPeUrlLoader",
    project_urls={
        "Github": "https://github.com/mauricelambert/PyPeUrlLoader",
        "Documentation": "https://mauricelambert.github.io/info/python/security/PyPeUrlLoader.html",
        "Python Executable": "https://mauricelambert.github.io/info/python/security/PyPeUrlLoader.pyz",
        "Windows Executable": "https://mauricelambert.github.io/info/python/security/PyPeUrlLoader.exe",
    },
    download_url="https://mauricelambert.github.io/info/python/security/PyPeUrlLoader.pyz",
    include_package_data=True,
    classifiers=[
        "Topic :: System",
        "Topic :: Security",
        "Environment :: Console",
        "Topic :: System :: Shells",
        "Natural Language :: English",
        "Programming Language :: Python",
        "Intended Audience :: Developers",
        "Topic :: System :: System Shells",
        "Programming Language :: Python :: 3.8",
        "Operating System :: Microsoft :: Windows",
        "Topic :: System :: Systems Administration",
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: System Administrators",
        "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    ],
    keywords=[
        "PeLoader",
        "URL",
        "LoadPeFromUrl",
        "MemoryExecution",
        "Fileless",
        "FilelessExecution",
        "HTTP",
        "LoadPeFromHttp",
    ],
    platforms=["Windows"],
    license="GPL-3.0 License",
    entry_points={
        "console_scripts": ["PyPeUrlLoader = PyPeUrlLoader:main"],
    },
    python_requires=">=3.8",
)
