# Generated by Django 4.2.8 on 2023-12-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exhibits", "0004_exhibitsorderable"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibitpage",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
