# Generated by Django 4.2.9 on 2024-01-10 20:56

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("exhibits", "0006_alter_exhibitpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exhibitpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", wagtail.blocks.RichTextBlock()),
                    (
                        "heading",
                        wagtail.blocks.RichTextBlock(
                            features=["italic"], form_classname="title", icon="title"
                        ),
                    ),
                    (
                        "subheading",
                        wagtail.blocks.RichTextBlock(
                            features=["italic"], form_classname="title", icon="title"
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
