"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .notfounderroruri import NotFoundErrorURI
from langcache import utils
from langcache.types import BaseModel
from typing import Optional


class NotFoundErrorResponseContentData(BaseModel):
    title: str
    r"""A short, human-readable summary of the problem type"""

    type: NotFoundErrorURI

    status: Optional[int] = 404
    r"""The HTTP status code generated by the origin server for this occurrence of the problem"""

    detail: Optional[str] = None
    r"""A human-readable explanation specific to this occurrence of the problem"""


class NotFoundErrorResponseContent(Exception):
    data: NotFoundErrorResponseContentData

    def __init__(self, data: NotFoundErrorResponseContentData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, NotFoundErrorResponseContentData)
