# Generated by Django 5.2.2 on 2025-06-23 10:04

import django.core.validators
import django.db.models.deletion
import django_hls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoHLSMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='django_hls/uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mp3', 'm4a'])])),
                ('hls_file', models.FileField(blank=True, null=True, upload_to=django_hls.models.DjangoHLSMedia.upload_to_path)),
                ('key_file', models.FileField(blank=True, null=True, upload_to=django_hls.models.DjangoHLSMedia.upload_to_path)),
            ],
        ),
        migrations.CreateModel(
            name='HLSMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=django_hls.models.HLSMedia.upload_to_path)),
                ('stream_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='django_hls.djangohlsmedia')),
            ],
        ),
    ]
