#!/usr/bin/env bash

set -eux

uv publish --username=__token__ --password=pypi-AgEIcHlwaS5vcmcCJDExOThmNzY3LWIxMjItNGZlOS1iMzJkLTVjNmU3NzNmYjk1NgACDlsxLFsid3VqaW5nIl1dAAIsWzIsWyI0NGUwY2QxNC00ODM0LTQzN2MtYTkyNi1kZjNjYTk3OGEyNzUiXV0AAAYg9EmCN_HjMmfx5JXs7Hse6EzE5UGXMU0_5g8B9qLw8hI