collections = {
    "collections": [
        {
            "collectionCode": "BILLS",
            "collectionName": "Congressional Bills",
            "packageCount": 276493,
            "granuleCount": None,
        },
        {
            "collectionCode": "BILLSTATUS",
            "collectionName": "Congressional Bill Status",
            "packageCount": 161000,
            "granuleCount": None,
        },
        {
            "collectionCode": "BILLSUM",
            "collectionName": "Congressional Bill Summaries",
            "packageCount": 5245,
            "granuleCount": None,
        },
        {
            "collectionCode": "BUDGET",
            "collectionName": "United States Budget",
            "packageCount": 387,
            "granuleCount": 7002,
        },
        {
            "collectionCode": "CCAL",
            "collectionName": "Congressional Calendars",
            "packageCount": 5989,
            "granuleCount": 96335,
        },
        {
            "collectionCode": "CDIR",
            "collectionName": "Congressional Directory",
            "packageCount": 237,
            "granuleCount": 15025,
        },
        {
            "collectionCode": "CDOC",
            "collectionName": "Congressional Documents",
            "packageCount": 53919,
            "granuleCount": 9982,
        },
        {
            "collectionCode": "CFR",
            "collectionName": "Code of Federal Regulations",
            "packageCount": 6433,
            "granuleCount": 7564580,
        },
        {
            "collectionCode": "CHRG",
            "collectionName": "Congressional Hearings",
            "packageCount": 45364,
            "granuleCount": 300,
        },
        {
            "collectionCode": "CMR",
            "collectionName": "Congressionally Mandated Reports",
            "packageCount": 742,
            "granuleCount": None,
        },
        {
            "collectionCode": "COMPS",
            "collectionName": "Statutes Compilations",
            "packageCount": 2617,
            "granuleCount": None,
        },
        {
            "collectionCode": "CPD",
            "collectionName": "Compilation of Presidential Documents",
            "packageCount": 17329,
            "granuleCount": 23012,
        },
        {
            "collectionCode": "CPRT",
            "collectionName": "Congressional Committee Prints",
            "packageCount": 5049,
            "granuleCount": 1850,
        },
        {
            "collectionCode": "CREC",
            "collectionName": "Congressional Record",
            "packageCount": 5762,
            "granuleCount": 827979,
        },
        {
            "collectionCode": "CRECB",
            "collectionName": "Congressional Record (Bound Edition)",
            "packageCount": 2412,
            "granuleCount": 472361,
        },
        {
            "collectionCode": "CRI",
            "collectionName": "Congressional Record Index",
            "packageCount": 43,
            "granuleCount": 624094,
        },
        {
            "collectionCode": "CRPT",
            "collectionName": "Congressional Reports",
            "packageCount": 106350,
            "granuleCount": 569,
        },
        {
            "collectionCode": "CZIC",
            "collectionName": "Coastal Zone Information Center",
            "packageCount": 4887,
            "granuleCount": None,
        },
        {
            "collectionCode": "ECFR",
            "collectionName": "Electronic Code of Federal Regulations",
            "packageCount": 49,
            "granuleCount": None,
        },
        {
            "collectionCode": "ECONI",
            "collectionName": "Economic Indicators",
            "packageCount": 362,
            "granuleCount": 17372,
        },
        {
            "collectionCode": "ERIC",
            "collectionName": "Education Reports from ERIC",
            "packageCount": 573,
            "granuleCount": None,
        },
        {
            "collectionCode": "ERP",
            "collectionName": "Economic Report of the President",
            "packageCount": 40,
            "granuleCount": 2960,
        },
        {
            "collectionCode": "FR",
            "collectionName": "Federal Register",
            "packageCount": 22499,
            "granuleCount": 980194,
        },
        {
            "collectionCode": "GAOREPORTS",
            "collectionName": "Government Accountability Office Reports and Comptroller General Decisions",
            "packageCount": 16569,
            "granuleCount": None,
        },
        {
            "collectionCode": "GOVMAN",
            "collectionName": "United States Government Manual",
            "packageCount": 28,
            "granuleCount": 5129,
        },
        {
            "collectionCode": "GOVPUB",
            "collectionName": "Bulk Submission",
            "packageCount": 114993,
            "granuleCount": 327,
        },
        {
            "collectionCode": "GPO",
            "collectionName": "Additional Government Publications",
            "packageCount": 4325,
            "granuleCount": 80571,
        },
        {
            "collectionCode": "HJOURNAL",
            "collectionName": "Journal of the House of Representatives",
            "packageCount": 153,
            "granuleCount": 33948,
        },
        {
            "collectionCode": "HMAN",
            "collectionName": "House Rules and Manual",
            "packageCount": 25,
            "granuleCount": 2282,
        },
        {
            "collectionCode": "HOB",
            "collectionName": "History of Bills",
            "packageCount": 43,
            "granuleCount": 312849,
        },
        {
            "collectionCode": "LSA",
            "collectionName": "List of CFR Sections Affected",
            "packageCount": 344,
            "granuleCount": 17826,
        },
        {
            "collectionCode": "PAI",
            "collectionName": "Privacy Act Issuances",
            "packageCount": 1590,
            "granuleCount": None,
        },
        {
            "collectionCode": "PLAW",
            "collectionName": "Public and Private Laws",
            "packageCount": 5913,
            "granuleCount": None,
        },
        {
            "collectionCode": "PPP",
            "collectionName": "Public Papers of the Presidents of the United States",
            "packageCount": 180,
            "granuleCount": 24847,
        },
        {
            "collectionCode": "SERIALSET",
            "collectionName": "Congressional Serial Set",
            "packageCount": 146880,
            "granuleCount": None,
        },
        {
            "collectionCode": "SJOURNAL",
            "collectionName": "Journal of the Senate",
            "packageCount": 171,
            "granuleCount": None,
        },
        {
            "collectionCode": "SMAN",
            "collectionName": "Senate Manual",
            "packageCount": 14,
            "granuleCount": 1386,
        },
        {
            "collectionCode": "STATUTE",
            "collectionName": "Statutes at Large",
            "packageCount": 134,
            "granuleCount": 115515,
        },
        {
            "collectionCode": "USCODE",
            "collectionName": "United States Code",
            "packageCount": 1505,
            "granuleCount": 1956865,
        },
        {
            "collectionCode": "USCOURTS",
            "collectionName": "United States Courts Opinions",
            "packageCount": 2002132,
            "granuleCount": 4314960,
        },
    ]
}

bills = {
    "count": 43,
    "message": None,
    "nextPage": None,
    "previousPage": None,
    "packages": [
        {
            "packageId": "BILLS-119hres536ih",
            "lastModified": "2025-06-24T10:13:34Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119hres536ih/summary",
            "docClass": "hres",
            "title": "Supporting the designation of the week including June 23, 2025, as National Women’s Sports Week to celebrate the anniversary of the passage of title IX and the growth of women’s sports.",
            "congress": "119",
            "dateIssued": "2025-06-23",
        },
        {
            "packageId": "BILLS-119hres535ih",
            "lastModified": "2025-06-24T09:05:36Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119hres535ih/summary",
            "docClass": "hres",
            "title": "Recognizing June 24th as Public Safety Awareness Day to promote citizen empowerment, effective law enforcement, community-based crime prevention, and prudent public policy in support of safer neighborhoods nationwide.",
            "congress": "119",
            "dateIssued": "2025-06-23",
        },
        {
            "packageId": "BILLS-119hres534ih",
            "lastModified": "2025-06-24T08:33:30Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119hres534ih/summary",
            "docClass": "hres",
            "title": "To commemorate the enactment of title IX and to celebrate the contributions women and girls make in education and athletics.",
            "congress": "119",
            "dateIssued": "2025-06-23",
        },
        {
            "packageId": "BILLS-119hres531ih",
            "lastModified": "2025-06-24T08:33:30Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119hres531ih/summary",
            "docClass": "hres",
            "title": "Recognizing the contributions of academic medicine and observing Academic Medicine Week from June 23 through 27, 2025.",
            "congress": "119",
            "dateIssued": "2025-06-23",
        },
        {
            "packageId": "BILLS-119hres532ih",
            "lastModified": "2025-06-24T08:33:26Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119hres532ih/summary",
            "docClass": "hres",
            "title": "Supporting the designation of Brain and Spine Metastasis Awareness Month.",
            "congress": "119",
            "dateIssued": "2025-06-23",
        },
        {
            "packageId": "BILLS-119hres533ih",
            "lastModified": "2025-06-24T08:33:25Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119hres533ih/summary",
            "docClass": "hres",
            "title": "Reaffirming the importance of the United States promoting the safety, health, and well-being of refugees and displaced persons in the United States and around the world.",
            "congress": "119",
            "dateIssued": "2025-06-23",
        },
        {
            "packageId": "BILLS-119hconres40ih",
            "lastModified": "2025-06-24T08:33:25Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119hconres40ih/summary",
            "docClass": "hconres",
            "title": "Directing the President, pursuant to section 5(c) of the War Powers Resolution, to remove United States Armed Forces from hostilities with Iran.",
            "congress": "119",
            "dateIssued": "2025-06-23",
        },
        {
            "packageId": "BILLS-119hres529ih",
            "lastModified": "2025-06-24T08:33:20Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119hres529ih/summary",
            "docClass": "hres",
            "title": "Honoring and celebrating National Boys and Girls Club Week of 2025.",
            "congress": "119",
            "dateIssued": "2025-06-23",
        },
        {
            "packageId": "BILLS-119hr3633rh",
            "lastModified": "2025-06-24T07:18:17Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119hr3633rh/summary",
            "docClass": "hr",
            "title": "Digital Asset Market Clarity Act of 2025",
            "congress": "119",
            "dateIssued": "2025-06-23",
        },
        {
            "packageId": "BILLS-119hres530rh",
            "lastModified": "2025-06-24T06:23:20Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119hres530rh/summary",
            "docClass": "hres",
            "title": "Providing for consideration of the bill (H.R. 3944) making appropriations for military construction, the Department of Veterans Affairs, and related agencies for the fiscal year ending September 30, 2026, and for other purposes; providing for consideration of the bill (H.R. 275) to require the Secretary of Homeland Security to publish on a monthly basis the number of special interest aliens encountered attempting to unlawfully enter the United States, and for other purposes; providing for consideration of the bill (H.R. 875) to amend the Immigration and Nationality Act to provide that aliens who have been convicted of or who have committed an offense for driving while intoxicated or impaired are inadmissible and deportable; and providing for consideration of the resolution (H. Res. 516) condemning the violent June 2025 riots in Los Angeles, California.",
            "congress": "119",
            "dateIssued": "2025-06-23",
        },
        {
            "packageId": "BILLS-119hr4071ih",
            "lastModified": "2025-06-24T06:23:20Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119hr4071ih/summary",
            "docClass": "hr",
            "title": "Combatting International Drug Trafficking and Human Smuggling Partnership Act of 2025",
            "congress": "119",
            "dateIssued": "2025-06-23",
        },
        {
            "packageId": "BILLS-119hr4070ih",
            "lastModified": "2025-06-24T06:23:16Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119hr4070ih/summary",
            "docClass": "hr",
            "title": "Tren de Aragua Border Security Threat Assessment Act",
            "congress": "119",
            "dateIssued": "2025-06-23",
        },
        {
            "packageId": "BILLS-119hr4058ih",
            "lastModified": "2025-06-24T05:25:54Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119hr4058ih/summary",
            "docClass": "hr",
            "title": "Enhancing Stakeholder Support and Outreach for Preparedness Grants Act",
            "congress": "119",
            "dateIssued": "2025-06-20",
        },
        {
            "packageId": "BILLS-119hr4007ih",
            "lastModified": "2025-06-24T05:25:54Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119hr4007ih/summary",
            "docClass": "hr",
            "title": "Prevent Halting of Active Research Act of 2025; PHARA Act of 2025",
            "congress": "119",
            "dateIssued": "2025-06-12",
        },
        {
            "packageId": "BILLS-119hr4004ih",
            "lastModified": "2025-06-24T05:25:54Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119hr4004ih/summary",
            "docClass": "hr",
            "title": "No Anonymity in Immigration Enforcement Act of 2025",
            "congress": "119",
            "dateIssued": "2025-06-12",
        },
        {
            "packageId": "BILLS-119hr4008ih",
            "lastModified": "2025-06-24T05:25:49Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119hr4008ih/summary",
            "docClass": "hr",
            "title": "Pay Our Correctional Officers Fairly Act",
            "congress": "119",
            "dateIssued": "2025-06-12",
        },
        {
            "packageId": "BILLS-119hr3978ih",
            "lastModified": "2025-06-24T05:25:49Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119hr3978ih/summary",
            "docClass": "hr",
            "title": "Nuclear REFUEL (Recycling Efficient Fuels Utilizing Expedited Licensing) Act",
            "congress": "119",
            "dateIssued": "2025-06-12",
        },
        {
            "packageId": "BILLS-119hr3980ih",
            "lastModified": "2025-06-24T05:25:48Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119hr3980ih/summary",
            "docClass": "hr",
            "title": "Streamline Emergency Care Act",
            "congress": "119",
            "dateIssued": "2025-06-12",
        },
        {
            "packageId": "BILLS-119hr4054ih",
            "lastModified": "2025-06-24T05:25:43Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119hr4054ih/summary",
            "docClass": "hr",
            "title": "Accreditation Choice and Innovation Act",
            "congress": "119",
            "dateIssued": "2025-06-20",
        },
        {
            "packageId": "BILLS-119hr3977ih",
            "lastModified": "2025-06-24T05:25:43Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119hr3977ih/summary",
            "docClass": "hr",
            "title": "Campus Housing Affordability for Foster Youth Act",
            "congress": "119",
            "dateIssued": "2025-06-12",
        },
        {
            "packageId": "BILLS-119hr4057ih",
            "lastModified": "2025-06-24T05:25:38Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119hr4057ih/summary",
            "docClass": "hr",
            "title": "CBP Canine Home Kenneling Pilot Act",
            "congress": "119",
            "dateIssued": "2025-06-20",
        },
        {
            "packageId": "BILLS-119hr4003ih",
            "lastModified": "2025-06-24T05:25:38Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119hr4003ih/summary",
            "docClass": "hr",
            "title": "Economic Opportunity for Border Communities Act",
            "congress": "119",
            "dateIssued": "2025-06-12",
        },
        {
            "packageId": "BILLS-119hr4002ih",
            "lastModified": "2025-06-24T05:25:38Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119hr4002ih/summary",
            "docClass": "hr",
            "title": "Patient Access to Higher Quality Health Care Act of 2025",
            "congress": "119",
            "dateIssued": "2025-06-12",
        },
        {
            "packageId": "BILLS-119hr42enr",
            "lastModified": "2025-06-24T04:01:56Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119hr42enr/summary",
            "docClass": "hr",
            "title": "Alaska Native Settlement Trust Eligibility Act",
            "congress": "119",
            "dateIssued": "2025-06-24",
        },
        {
            "packageId": "BILLS-119hr2215enr",
            "lastModified": "2025-06-24T04:01:56Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119hr2215enr/summary",
            "docClass": "hr",
            "title": "Salem Maritime National Historical Park Redesignation and Boundary Study Act",
            "congress": "119",
            "dateIssued": "2025-06-24",
        },
        {
            "packageId": "BILLS-119hr3994ih",
            "lastModified": "2025-06-24T04:01:51Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119hr3994ih/summary",
            "docClass": "hr",
            "title": "Understanding Student Parent Outcomes Act of 2025",
            "congress": "119",
            "dateIssued": "2025-06-12",
        },
        {
            "packageId": "BILLS-119hr618enr",
            "lastModified": "2025-06-24T04:01:50Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119hr618enr/summary",
            "docClass": "hr",
            "title": "Apex Area Technical Corrections Act",
            "congress": "119",
            "dateIssued": "2025-06-24",
        },
        {
            "packageId": "BILLS-119hr3993ih",
            "lastModified": "2025-06-24T04:01:44Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119hr3993ih/summary",
            "docClass": "hr",
            "title": "Preserving Great Americans’ Legacies Act of 2025",
            "congress": "119",
            "dateIssued": "2025-06-12",
        },
        {
            "packageId": "BILLS-119hr3991ih",
            "lastModified": "2025-06-24T04:01:44Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119hr3991ih/summary",
            "docClass": "hr",
            "title": "Research for Healthy Soils Act",
            "congress": "119",
            "dateIssued": "2025-06-12",
        },
        {
            "packageId": "BILLS-119hr3992ih",
            "lastModified": "2025-06-24T04:01:40Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119hr3992ih/summary",
            "docClass": "hr",
            "title": "Republic of Somaliland Independence Act",
            "congress": "119",
            "dateIssued": "2025-06-12",
        },
        {
            "packageId": "BILLS-119s2043is",
            "lastModified": "2025-06-24T03:56:10Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119s2043is/summary",
            "docClass": "s",
            "title": "Open America's Waters Act",
            "congress": "119",
            "dateIssued": "2025-06-12",
        },
        {
            "packageId": "BILLS-119sres289is",
            "lastModified": "2025-06-24T03:56:05Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119sres289is/summary",
            "docClass": "sres",
            "title": "Recognizing the importance of pollinators to ecosystem health and agriculture in the United States by designating June 15 through June 22, 2025, as National Pollinator Week.",
            "congress": "119",
            "dateIssued": "2025-06-18",
        },
        {
            "packageId": "BILLS-119sres287is",
            "lastModified": "2025-06-24T03:56:05Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119sres287is/summary",
            "docClass": "sres",
            "title": "Reaffirming the importance of the United States promoting the safety, health, and well-being of refugees and displaced persons in the United States and around the world.",
            "congress": "119",
            "dateIssued": "2025-06-18",
        },
        {
            "packageId": "BILLS-119s2052is",
            "lastModified": "2025-06-24T03:56:05Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119s2052is/summary",
            "docClass": "s",
            "title": "Flood Insurance Transparency Act of 2025",
            "congress": "119",
            "dateIssued": "2025-06-12",
        },
        {
            "packageId": "BILLS-119sres288is",
            "lastModified": "2025-06-24T03:56:00Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119sres288is/summary",
            "docClass": "sres",
            "title": "Condemning the rise in ideologically motivated attacks on Jewish individuals in the United States, including the recent violent assault in Boulder, Colorado, and reaffirming the commitment of the Senate to combating antisemitism and politically motivated violence.",
            "congress": "119",
            "dateIssued": "2025-06-18",
        },
        {
            "packageId": "BILLS-119s2044is",
            "lastModified": "2025-06-24T03:56:00Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119s2044is/summary",
            "docClass": "s",
            "title": "Office of Fossil Energy and Carbon Management Relocation Act of 2025",
            "congress": "119",
            "dateIssued": "2025-06-12",
        },
        {
            "packageId": "BILLS-119hr43enr",
            "lastModified": "2025-06-24T03:55:58Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119hr43enr/summary",
            "docClass": "hr",
            "title": "Alaska Native Village Municipal Lands Restoration Act of 2025",
            "congress": "119",
            "dateIssued": "2025-06-24",
        },
        {
            "packageId": "BILLS-119sres291is",
            "lastModified": "2025-06-24T03:55:55Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119sres291is/summary",
            "docClass": "sres",
            "title": "Celebrating the June 2025 North Atlantic Treaty Organization Summit in the Hague, the Netherlands, and reaffirming priorities pertaining to transatlantic security and our commitment to NATO.",
            "congress": "119",
            "dateIssued": "2025-06-18",
        },
        {
            "packageId": "BILLS-119s2045is",
            "lastModified": "2025-06-24T03:55:55Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119s2045is/summary",
            "docClass": "s",
            "title": "Protecting Endowments from Our Adversaries Act",
            "congress": "119",
            "dateIssued": "2025-06-12",
        },
        {
            "packageId": "BILLS-119s2047is",
            "lastModified": "2025-06-24T03:55:53Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119s2047is/summary",
            "docClass": "s",
            "title": "No Capital Gains Allowance for American Adversaries Act",
            "congress": "119",
            "dateIssued": "2025-06-12",
        },
        {
            "packageId": "BILLS-119hr4006ih",
            "lastModified": "2025-06-24T03:55:48Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119hr4006ih/summary",
            "docClass": "hr",
            "title": "Mission Utilize No Phones in Learning to Unleash Growth in Grades and Educate Distraction-free Act; Mission UNPLUGGED Act",
            "congress": "119",
            "dateIssued": "2025-06-12",
        },
        {
            "packageId": "BILLS-119s2046is",
            "lastModified": "2025-06-24T03:55:45Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-119s2046is/summary",
            "docClass": "s",
            "title": "No China in Index Funds Act",
            "congress": "119",
            "dateIssued": "2025-06-12",
        },
        {
            "packageId": "BILLS-118hconres33ih",
            "lastModified": "2025-06-23T14:53:26Z",
            "packageLink": "https://api.govinfo.gov/packages/BILLS-118hconres33ih/summary",
            "docClass": "hconres",
            "title": "Freedom to Decide Act",
            "congress": "118",
            "dateIssued": "2023-04-13",
        },
    ],
}
