json_data = [
    {
        "city": "Ahmedabad",
        "zone": "Bapunagar",
        "fleet": "Food",
        "classification": "Critical",
        "21day_orders": 400,
        "21day_bonus": 6000,
        "total_bonus": 6000,
        "bag_price": 199,
        "nearest_zone": "naroda, maninagar",
    },
    {
        "city": "Ahmedabad",
        "zone": "Bopal",
        "fleet": "Food",
        "classification": "Focus",
        "21day_orders": 475,
        "21day_bonus": 6000,
        "total_bonus": 6000,
        "bag_price": 199,
        "nearest_zone": "vastrapur, prahladnagar",
    },
    {
        "city": "Ahmedabad",
        "zone": "Chandkheda",
        "fleet": "Food",
        "classification": "Critical",
        "21day_orders": 400,
        "21day_bonus": 6000,
        "total_bonus": 6000,
        "bag_price": 199,
        "nearest_zone": "gota, naranpura",
    },
    {
        "city": "Ahmedabad",
        "zone": "Gandhinagar",
        "fleet": "Food",
        "classification": "No Bonus",
        "21day_orders": 0,
        "21day_bonus": 0,
        "total_bonus": 0,
        "bag_price": 99,
        "nearest_zone": "no near by zone",
    },
    {
        "city": "Ahmedabad",
        "zone": "Ghatlodia",
        "fleet": "Food",
        "classification": "Focus",
        "21day_orders": 475,
        "21day_bonus": 6000,
        "total_bonus": 6000,
        "bag_price": 199,
        "nearest_zone": "gota, vastrapur",
    },
    {
        "city": "Ahmedabad",
        "zone": "GOTA",
        "fleet": "Food",
        "classification": "Critical",
        "21day_orders": 400,
        "21day_bonus": 6000,
        "total_bonus": 6000,
        "bag_price": 199,
        "nearest_zone": "chandkheda, ghatlodia",
    },
    {
        "city": "Ahmedabad",
        "zone": "Isanpur",
        "fleet": "Food",
        "classification": "Non Critical",
        "21day_orders": 350,
        "21day_bonus": 5250,
        "total_bonus": 5250,
        "bag_price": 199,
        "nearest_zone": "maninagar, paldi&ambawadi",
    },
    {
        "city": "Ahmedabad",
        "zone": "Kalol",
        "fleet": "Food",
        "classification": "Focus",
        "21day_orders": 0,
        "21day_bonus": 0,
        "total_bonus": 0,
        "bag_price": 199,
        "nearest_zone": "inactive zone",
    },
    {
        "city": "Ahmedabad",
        "zone": "Maninagar",
        "fleet": "Food",
        "classification": "Critical",
        "21day_orders": 400,
        "21day_bonus": 6000,
        "total_bonus": 6000,
        "bag_price": 199,
        "nearest_zone": "isanpur, naroda",
    },
    {
        "city": "Ahmedabad",
        "zone": "Naranpura",
        "fleet": "Food",
        "classification": "Focus",
        "21day_orders": 475,
        "21day_bonus": 6000,
        "total_bonus": 6000,
        "bag_price": 199,
        "nearest_zone": "ghatlodia, chandkheda",
    },
    {
        "city": "Ahmedabad",
        "zone": "Naroda",
        "fleet": "Food",
        "classification": "No Bonus",
        "21day_orders": 350,
        "21day_bonus": 5250,
        "total_bonus": 5250,
        "bag_price": 2,
        "nearest_zone": "bapunagar, maninagar",
    },
    {
        "city": "Ahmedabad",
        "zone": "Navrangpura",
        "fleet": "Food",
        "classification": "Critical",
        "21day_orders": 500,
        "21day_bonus": 4500,
        "total_bonus": 4500,
        "bag_price": 199,
        "nearest_zone": "ghatlodia, narannpura",
    },
    {
        "city": "Ahmedabad",
        "zone": "Paldi & Ambawadi",
        "fleet": "Food",
        "classification": "Focus",
        "21day_orders": 475,
        "21day_bonus": 6000,
        "total_bonus": 6000,
        "bag_price": 199,
        "nearest_zone": "navrangpura, maninagar",
    },
    {
        "city": "Ahmedabad",
        "zone": "Prahlad Nagar",
        "fleet": "Food",
        "classification": "Critical",
        "21day_orders": 520,
        "21day_bonus": 6000,
        "total_bonus": 6000,
        "bag_price": 199,
        "nearest_zone": "paldi&ambawadi, vastrapur",
    },
    {
        "city": "Ahmedabad",
        "zone": "Vastrapur",
        "fleet": "Food",
        "classification": "Non Critical",
        "21day_orders": 450,
        "21day_bonus": 4500,
        "total_bonus": 4500,
        "bag_price": 199,
        "nearest_zone": "prahlad nagar, ghatlodia",
    },
    {
        "city": "Ahmedabad",
        "zone": "Changodar",
        "fleet": "Food",
        "classification": "Focus",
        "21day_orders": 0,
        "21day_bonus": 0,
        "total_bonus": 0,
        "bag_price": 199,
        "nearest_zone": "inactive zone",
    },
    {
        "city": "Ahmedabad",
        "zone": "Sanand",
        "fleet": "Food",
        "classification": "Critical",
        "21day_orders": 0,
        "21day_bonus": 0,
        "total_bonus": 0,
        "bag_price": 199,
        "nearest_zone": "stop hiring if hiring is full",
    },
    {
        "city": "Ahmedabad",
        "zone": "Bapunagar",
        "fleet": "Instamart",
        "classification": "Non Critical",
        "21day_orders": 350,
        "21day_bonus": 3000,
        "total_bonus": 3000,
        "bag_price": 199,
        "nearest_zone": "Isanpur",
    },
    {
        "city": "Ahmedabad",
        "zone": "Bopal",
        "fleet": "Instamart",
        "classification": "Focus",
        "21day_orders": 540,
        "21day_bonus": 6000,
        "total_bonus": 6000,
        "bag_price": 199,
        "nearest_zone": "Vastrapur, Prahlad nagar",
    },
    {
        "city": "Ahmedabad",
        "zone": "Chandkheda",
        "fleet": "Instamart",
        "classification": "No Bonus",
        "21day_orders": 0,
        "21day_bonus": 0,
        "total_bonus": 0,
        "bag_price": 199,
        "nearest_zone": "Gandhinagar, Gota",
    },
    {
        "city": "Ahmedabad",
        "zone": "Changodar",
        "fleet": "Instamart",
        "classification": "No Bonus",
        "21day_orders": 0,
        "21day_bonus": 0,
        "total_bonus": 0,
        "bag_price": 199,
        "nearest_zone": "Not operational",
    },
    {
        "city": "Ahmedabad",
        "zone": "Gandhinagar",
        "fleet": "Instamart",
        "classification": "Critical",
        "21day_orders": 430,
        "21day_bonus": 4500,
        "total_bonus": 4500,
        "bag_price": 199,
        "nearest_zone": "no near by zone",
    },
    {
        "city": "Ahmedabad",
        "zone": "Ghatlodia",
        "fleet": "Instamart",
        "classification": "Critical",
        "21day_orders": 570,
        "21day_bonus": 4500,
        "total_bonus": 4500,
        "bag_price": 199,
        "nearest_zone": "Vastrapur, Gota",
    },
    {
        "city": "Ahmedabad",
        "zone": "GOTA",
        "fleet": "Instamart",
        "classification": "Focus",
        "21day_orders": 480,
        "21day_bonus": 5500,
        "total_bonus": 5500,
        "bag_price": 2,
        "nearest_zone": "Ghatlodia",
    },
    {
        "city": "Ahmedabad",
        "zone": "Isanpur",
        "fleet": "Instamart",
        "classification": "No Bonus",
        "21day_orders": 350,
        "21day_bonus": 2800,
        "total_bonus": 2800,
        "bag_price": 199,
        "nearest_zone": "Bapunagar",
    },
    {
        "city": "Ahmedabad",
        "zone": "Kalol",
        "fleet": "Instamart",
        "classification": "No Bonus",
        "21day_orders": 0,
        "21day_bonus": 0,
        "total_bonus": 0,
        "bag_price": 199,
        "nearest_zone": "Gandhinagar, Chandkheda",
    },
    {
        "city": "Ahmedabad",
        "zone": "Maninagar",
        "fleet": "Instamart",
        "classification": "No Bonus",
        "21day_orders": 350,
        "21day_bonus": 2800,
        "total_bonus": 2800,
        "bag_price": 199,
        "nearest_zone": "Not operational",
    },
    {
        "city": "Ahmedabad",
        "zone": "Naranpura",
        "fleet": "Instamart",
        "classification": "No Bonus",
        "21day_orders": 0,
        "21day_bonus": 0,
        "total_bonus": 0,
        "bag_price": 199,
        "nearest_zone": "Gota, Ghatlodia",
    },
    {
        "city": "Ahmedabad",
        "zone": "Naroda",
        "fleet": "Instamart",
        "classification": "No Bonus",
        "21day_orders": 350,
        "21day_bonus": 2800,
        "total_bonus": 2800,
        "bag_price": 199,
        "nearest_zone": "Not operational",
    },
    {
        "city": "Ahmedabad",
        "zone": "Navrangpura",
        "fleet": "Instamart",
        "classification": "Critical",
        "21day_orders": 380,
        "21day_bonus": 3000,
        "total_bonus": 3000,
        "bag_price": 199,
        "nearest_zone": "Ghatlodia, Vastrapur",
    },
    {
        "city": "Ahmedabad",
        "zone": "Paldi & Ambawadi",
        "fleet": "Instamart",
        "classification": "No Bonus",
        "21day_orders": 0,
        "21day_bonus": 0,
        "total_bonus": 0,
        "bag_price": 49,
        "nearest_zone": "Vastrapur, Navrangpura",
    },
    {
        "city": "Ahmedabad",
        "zone": "Prahlad Nagar",
        "fleet": "Instamart",
        "classification": "Non Critical",
        "21day_orders": 460,
        "21day_bonus": 2500,
        "total_bonus": 2500,
        "bag_price": 199,
        "nearest_zone": "Bopal, Vastrapur",
    },
    {
        "city": "Ahmedabad",
        "zone": "Sanand",
        "fleet": "Instamart",
        "classification": "No Bonus",
        "21day_orders": 0,
        "21day_bonus": 0,
        "total_bonus": 0,
        "bag_price": 49,
        "nearest_zone": "Not operational",
    },
    {
        "city": "Ahmedabad",
        "zone": "Vastrapur",
        "fleet": "Instamart",
        "classification": "Critical",
        "21day_orders": 570,
        "21day_bonus": 2500,
        "total_bonus": 2500,
        "bag_price": 199,
        "nearest_zone": "Bopal, Ghatlodia",
    },
]
