# coding: utf-8

"""
    AristaFlowREST/ResModelManager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import af_res_model_manager
from af_res_model_manager.api.res_inst_remote_iterator_api import ResInstRemoteIteratorApi  # noqa: E501
from af_res_model_manager.rest import ApiException


class TestResInstRemoteIteratorApi(unittest.TestCase):
    """ResInstRemoteIteratorApi unit test stubs"""

    def setUp(self):
        self.api = ResInstRemoteIteratorApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_res_expr_eval_close(self):
        """Test case for res_expr_eval_close

        """
        pass

    def test_res_expr_eval_get_next(self):
        """Test case for res_expr_eval_get_next

        """
        pass

    def test_res_expr_eval_get_previous(self):
        """Test case for res_expr_eval_get_previous

        """
        pass

    def test_res_expr_eval_keep_alive(self):
        """Test case for res_expr_eval_keep_alive

        """
        pass

    def test_res_inst_close(self):
        """Test case for res_inst_close

        """
        pass

    def test_res_inst_get_next(self):
        """Test case for res_inst_get_next

        """
        pass

    def test_res_inst_get_previous(self):
        """Test case for res_inst_get_previous

        """
        pass

    def test_res_inst_keep_alive(self):
        """Test case for res_inst_keep_alive

        """
        pass


if __name__ == '__main__':
    unittest.main()
