# coding: utf-8

"""
    AristaFlowREST/ResModelManager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import af_res_model_manager
from af_res_model_manager.models.light_weight_process import LightWeightProcess  # noqa: E501
from af_res_model_manager.rest import ApiException


class TestLightWeightProcess(unittest.TestCase):
    """LightWeightProcess unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLightWeightProcess(self):
        """Test LightWeightProcess"""
        # FIXME: construct object with mandatory attributes with example values
        # model = af_res_model_manager.models.light_weight_process.LightWeightProcess()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
