iller = {
    
  "01": {"ad":"Adana","bolge":"Akdeniz","yapilar":["Taşköprü","Büyük Saat","Sabancı Merkez Camii"],"urunler":["pamuk","nar","fıstık"]},
  "02": {"ad":"Adıyaman","bolge":"Güneydoğu Anadolu","yapilar":["Nemrut Dağı","Kahta Kalesi","Cendere Köprüsü"],"urunler":["ince bulgur","nar","üzüm"]},
  "03": {"ad":"Afyonkarahisar","bolge":"Ege","yapilar":["Afyon Kalesi","Ulu Camii","Zafer Müzesi"],"urunler":["haşhaş","kayısı","sucuk"]},
  "04": {"ad":"Ağrı","bolge":"Doğu Anadolu","yapilar":["Ağrı Dağı","İshak Paşa Sarayı","Doğubayazıt Kalesi"],"urunler":["bal","ceviz","uşağı"]},
  "05": {"ad":"Amasya","bolge":"Karadeniz","yapilar":["Yalıboyu Evleri","Amasya Kalesi","III. Beyazıd Türbesi"],"urunler":["elma","kiraz","ceviz"]},
  "06": {"ad":"Ankara","bolge":"İç Anadolu","yapilar":["Anıtkabir","Kocatepe Camii","Hacı Bayram"],"urunler":["leblebi","buğday","soğan"]},
  "07": {"ad":"Antalya","bolge":"Akdeniz","yapilar":["Hadrian Kapısı","Yivli Minare","Kaleiçi"],"urunler":["portakal","zeytin","narenciye"]},
  "08": {"ad":"Artvin","bolge":"Karadeniz","yapilar":["Şavşat Kalesi","Maral Şelalesi","Cehennem Deresi"],"urunler":["bal","fındık","kara lahana"]},
  "09": {"ad":"Aydın","bolge":"Ege","yapilar":["Tralleis Antik Kenti","Kuşadası Kaleiçi","Basilica Kilisesi"],"urunler":["incir","zeytin","üzüm"]},
  "10": {"ad":"Balıkesir","bolge":"Marmara","yapilar":["Ayvalık Tımarhanesi","Cunda Adası","Zeytinli Camii"],"urunler":["zeytin","zeytinyağı","peynir"]},
  "11": {"ad":"Bilecik","bolge":"Marmara","yapilar":["Şeyh Edebali Türbesi","Osmanlı Evi","Göksu Park"],"urunler":["şimşir","bal","buğday"]},
  "12": {"ad":"Bingöl","bolge":"Doğu Anadolu","yapilar":["Peri Bacaları","Yüzen Ada","Solhan Kalesi"],"urunler":["bal","ceviz","kiraz"]},
  "13": {"ad":"Bitlis","bolge":"Doğu Anadolu","yapilar":["Ahlat Türbeleri","Nemrut Krater Gölü","Bitlis Kalesi"],"urunler":["bal","üzüm","ceviz"]},
  "14": {"ad":"Bolu","bolge":"Karadeniz","yapilar":["Yedigöller","Gölcük","Kartalkaya"],"urunler":["mantar","bal","kara lahana"]},
  "15": {"ad":"Burdur","bolge":"Akdeniz","yapilar":["Salda Gölü","Burdur Müzesi","Gölhisar Kalesi"],"urunler":["elma","kiraz","bal"]},
  "16": {"ad":"Bursa","bolge":"Marmara","yapilar":["Uludağ","Ulu Camii","Yeşil Türbe"],"urunler":["peynir","zeytin","kiraz"]},
  "17": {"ad":"Çanakkale","bolge":"Marmara","yapilar":["Truva Antik Kenti","Çanakkale Şehitlik","Bozcaada Kalesi"],"urunler":["üzüm","zeytin","bal"]},
  "18": {"ad":"Çankırı","bolge":"İç Anadolu","yapilar":["Çankırı Kalesi","Kurşunlu Camii","Tuz Mağarası"],"urunler":["tuz","buğday","yumurta"]},
  "19": {"ad":"Çorum","bolge":"Karadeniz","yapilar":["Hattuşaş","Alacahöyük","Çorum Kalesi"],"urunler":["leblebi","buğday","ceviz"]},
  "20": {"ad":"Denizli","bolge":"Ege","yapilar":["Pamukkale","Laodikeia Antik Kenti","Dokuma Park"],"urunler":["pamuk","keçiboynuzu","elma"]},
  "21": {"ad":"Diyarbakır","bolge":"Güneydoğu Anadolu","yapilar":["Diyarbakır Surları","Ulu Camii","Hasan Paşa Hanı"],"urunler":["karpuz","patlıcan","buğday"]},
  "22": {"ad":"Edirne","bolge":"Marmara","yapilar":["Selimiye Camii","Eski Camii","Rüstem Paşa Kervansarayı"],"urunler":["peynir","üzüm","zeytin"]},
  "23": {"ad":"Elazığ","bolge":"Doğu Anadolu","yapilar":["Harput Kalesi","Gölpınar Gölü","Hazar Gölü"],"urunler":["üzüm","ceviz","bal"]},
  "24": {"ad":"Erzincan","bolge":"Doğu Anadolu","yapilar":["Kemaliye Evleri","Girlevik Şelalesi","Erzincan Kalesi"],"urunler":["abalı karpuz","elma","ceviz"]},
  "25": {"ad":"Erzurum","bolge":"Doğu Anadolu","yapilar":["Çifte Minareli Medrese","Palandöken","Yakutiye Medresesi"],"urunler":["deri","ceviz","bal"]},
  "26": {"ad":"Eskişehir","bolge":"İç Anadolu","yapilar":["Odunpazarı Evleri","Porsuk Çayı","Sazova Parkı"],"urunler":["böreklik un","bal","üzüm"]},
  "27": {"ad":"Gaziantep","bolge":"Güneydoğu Anadolu","yapilar":["Gaziantep Kalesi","Zeugma Mozaik Müzesi","Bakırcılar Çarşısı"],"urunler":["baklava","antepfıstığı","nar"]},
  "28": {"ad":"Giresun","bolge":"Karadeniz","yapilar":["Giresun Kalesi","Aksu Şelalesi","Güre Plajı"],"urunler":["fındık","bal","üzüm"]},
  "29": {"ad":"Gümüşhane","bolge":"Karadeniz","yapilar":["Santa Harabeleri","Karaca Mağarası","Bayburt Kalesi"],"urunler":["bal","ceviz","misket elması"]},
  "30": {"ad":"Hakkâri","bolge":"Doğu Anadolu","yapilar":["İkiyaka Dağları","Merga Bütan Geçidi","Şemdinli Kalesi"],"urunler":["ballıbaba armudu","ceviz","ballı bal"]},
  "31": {"ad":"Hatay","bolge":"Akdeniz","yapilar":["Saint Pierre Kilisesi","Antakya Mozaik Müzesi","Habib-i Neccar Camii"],"urunler":["zeytin","nar","biber salçası"]},
  "32": {"ad":"Isparta","bolge":"Akdeniz","yapilar":["Eğirdir Gölü","Isparta Gül Bahçeleri","Yalvaç Pisidia Antik Kenti"],"urunler":["gül", "elma","kiraz"]},
  "33": {"ad":"Mersin","bolge":"Akdeniz","yapilar":["Kızkalesi","Mamure Kalesi","Tarsus Şelalesi"],"urunler":["narenciye","zeytin","üzüm"]},
  "34": {"ad":"İstanbul","bolge":"Marmara","yapilar":["Ayasofya","Topkapı Sarayı","Galata Kulesi"],"urunler":["balık","zeytin","tahin"]},
  "35": {"ad":"İzmir","bolge":"Ege","yapilar":["Saat Kulesi","Kadifekale","Agora"],"urunler":["üzüm","zeytin","incir"]},
  "36": {"ad":"Kars","bolge":"Doğu Anadolu","yapilar":["Ani Harabeleri","Kars Kalesi","Fethiye Camii"],"urunler":["bal","kaşar peyniri","ceviz"]},
  "37": {"ad":"Kastamonu","bolge":"Karadeniz","yapilar":["Kastamonu Kalesi","Küre Dağları","Nasrullah Camii"],"urunler":["ceviz","bal","elma"]},
  "38": {"ad":"Kayseri","bolge":"İç Anadolu","yapilar":["Kapadokya","Erciyes","Hisarcık Kalesi"],"urunler":["pastırma","peynir","buğday"]},
  "39": {"ad":"Kırklareli","bolge":"Marmara","yapilar":["Dupnisa Mağarası","Uluköy Camii","Vize Kalesi"],"urunler":["üzüm","zeytin","bal"]},
  "40": {"ad":"Kırşehir","bolge":"İç Anadolu","yapilar":["Ahi Evran Türbesi","Cacabey Medresesi","Kırşehir Kalesi"],"urunler":["kiraz","büryan kebabı","buğday"]},
  "41": {"ad":"Kocaeli","bolge":"Marmara","yapilar":["Gayret Gemi Müzesi","Osman Hamdi Bey Müzesi","İzmit Saat Kulesi"],"urunler":["fındık","bal","zeytin"]},
  "42": {"ad":"Konya","bolge":"İç Anadolu","yapilar":["Mevlana Müzesi","Alaaddin Tepesi","İnce Minareli Medrese"],"urunler":["buğday","leblebi","fasulye"]},
  "43": {"ad":"Kütahya","bolge":"Ege","yapilar":["Kütahya Kalesi","Çinicilik Atölyeleri","Aizanoi"],"urunler":["çini", "buğday","fasulye"]},
  "44": {"ad":"Malatya","bolge":"Doğu Anadolu","yapilar":["Malatya Kalesi","Arslantepe Höyüğü","Nemrut Dağı"],"urunler":["kayısı","ceviz","bal"]},
  "45": {"ad":"Manisa","bolge":"Ege","yapilar":["Sardes Antik Kenti","Muradiye Şelalesi","Kula Evleri"],"urunler":["zeytin","üzüm","peynir"]},
  "46": {"ad":"Kahramanmaraş","bolge":"Güneydoğu Anadolu","yapilar":["Krak des Chevaliers","Taş Köprü","Arslantepe"],"urunler":["fıstık","biber salçası","ceviz"]},
  "47": {"ad":"Mardin","bolge":"Güneydoğu Anadolu","yapilar":["Deyrulzafaran Manastırı","Mardin Kalesi","Zinciriye Medresesi"],"urunler":["hurma","ceviz","bal"]},
  "48": {"ad":"Muğla","bolge":"Ege","yapilar":["Bodrum Kalesi","Ölüdeniz","Knidos"],"urunler":["zeytin","üzüm","bal"]},
  "49": {"ad":"Muş","bolge":"Doğu Anadolu","yapilar":["Muş Kalesi","Mercimekli Höyük","Karasu Nehri"],"urunler":["bal","ceviz","üzüm"]},
  "50": {"ad":"Nevşehir","bolge":"İç Anadolu","yapilar":["Göreme","Uçhisar Kalesi","Zelve"],"urunler":["üzüm","elma","ceviz"]},
  "51": {"ad":"Niğde","bolge":"İç Anadolu","yapilar":["Tyana Antik Kenti","Niğde Kalesi","Gümüşler Manastırı"],"urunler":["elma","kiraz","peynir"]},
  "52": {"ad":"Ordu","bolge":"Karadeniz","yapilar":["Perşembe Yaylası","Boztepe","Çambaşı Yaylası"],"urunler":["fındık","bal","üzüm"]},
  "53": {"ad":"Rize","bolge":"Karadeniz","yapilar":["Ayder Yaylası","Zilkale","Fırtına Vadisi"],"urunler":["çay","fındık","bal"]},
  "54": {"ad":"Sakarya","bolge":"Marmara","yapilar":["Sapanca Gölü","Karasu Plajı","Akıncılar Köyü"],"urunler":["fındık","üzüm","elma"]},
  "55": {"ad":"Samsun","bolge":"Karadeniz","yapilar":["Bandırma Vapuru","Amisos Tepesi","Gazi Müzesi"],"urunler":["ladin balı","fındık","üzüm"]},
  "56": {"ad":"Siirt","bolge":"Güneydoğu Anadolu","yapilar":["Veysel Karani Türbesi","Pervari Bal Ormanı","Eruh Çayı"],"urunler":["bal","ceviz","hurma"]},
  "57": {"ad":"Sinop","bolge":"Karadeniz","yapilar":["Sinop Kalesi","Hamsilos Fiyordu","Balatlar Kilisesi"],"urunler":["hamsi","fındık","bal"]},
  "58": {"ad":"Sivas","bolge":"Karadeniz","yapilar":["Divriği Ulu Camii","Kangal Balıklı Kaplıca","Sivas Kongre Binası"],"urunler":["kangal köpeği","ceviz","buğday"]},
  "59": {"ad":"Tekirdağ","bolge":"Marmara","yapilar":["Rüstem Paşa","Şarköy Plajı","Tekirdağ Saat Kulesi"],"urunler":["üzüm","zeytin","zeytinyağı"]},
  "60": {"ad":"Tokat","bolge":"Karadeniz","yapilar":["Tokat Kalesi","Ballıca Mağarası","Gök Medrese"],"urunler":["ceviz","elma","bal"]},
  "61": {"ad":"Trabzon","bolge":"Karadeniz","yapilar":["Sümela Manastırı","Uzungöl","Trabzon Kalesi"],"urunler":["fındık","bal","mıhlama malzemesi"]},
  "62": {"ad":"Tunceli","bolge":"Doğu Anadolu","yapilar":["Munzur Vadisi","Pertek Kalesi","Ovacık"],"urunler":["bal","ceviz","yaban mersini"]},
  "63": {"ad":"Şanlıurfa","bolge":"Güneydoğu Anadolu","yapilar":["Balıklıgöl","Urfa Kalesi","Göbeklitepe"],"urunler":["hurma","patlıcan","buğday"]},
  "64": {"ad":"Uşak","bolge":"Ege","yapilar":["Kurşunlu Kervansarayı","Porsuk Çayı","Atatürk Evi"],"urunler":["pamuk","üzüm","elma"]},
  "65": {"ad":"Van","bolge":"Doğu Anadolu","yapilar":["Van Kalesi","Akdamar Adası","Muradiye Şelalesi"],"urunler":["bal","otu peyniri","incir"]},
  "66": {"ad":"Yozgat","bolge":"İç Anadolu","yapilar":["Yozgat Kalesi","Çapanoğlu Camii","Kapuzbaşı Şelalesi"],"urunler":["buğday","elma","ceviz"]},
  "67": {"ad":"Zonguldak","bolge":"Karadeniz","yapilar":["Ereğli Kalesi","Filyos Antik Kenti","Zonguldak Müzesi"],"urunler":["fındık","bal","kömür"]},
  "68": {"ad":"Aksaray","bolge":"İç Anadolu","yapilar":["Ihlara Vadisi","Ağzıkarahan","Güzelyurt"],"urunler":["buğday","elma","üzüm"]},
  "69": {"ad":"Bayburt","bolge":"Karadeniz","yapilar":["Bayburt Kalesi","Mama Hatun Türbesi","Altıntaş Köprüsü"],"urunler":["bal","ceviz","üzüm"]},
  "70": {"ad":"Karaman","bolge":"İç Anadolu","yapilar":["Karaman Kalesi","Aziziye Camii","Ermenek Kalesi"],"urunler":["buğday","kiraz","elma"]},
  "71": {"ad":"Kırıkkale","bolge":"İç Anadolu","yapilar":["Macunköy Bağdatlı Camii","Delice Çayı","Silah Sanayi Müzesi"],"urunler":["buğday","bal","tavuk"]},
  "72": {"ad":"Batman","bolge":"Güneydoğu Anadolu","yapilar":["Hasankeyf","Malabadi Köprüsü","Rhesaina Antik Kenti"],"urunler":["hurma","ceviz","bal"]},
  "73": {"ad":"Şırnak","bolge":"Güneydoğu Anadolu","yapilar":["Cudi Dağı","Şırnak Kalesi","Uludere Çayı"],"urunler":["bal","ceviz","üzüm"]},
  "74": {"ad":"Bartın","bolge":"Karadeniz","yapilar":["Amasra","Bartın Nehri","Takoz Tepesi"],"urunler":["bal","fındık","üzüm"]},
  "75": {"ad":"Ardahan","bolge":"Doğu Anadolu","yapilar":["Çıldır Gölü","Göle Kalesi","Hanak Yaylası"],"urunler":["bal","ceviz","balık"]},
  "76": {"ad":"Iğdır","bolge":"Doğu Anadolu","yapilar":["Ağrı Dağı","Iğdır Kalesi","Suphan Dağı"],"urunler":["bal","ceviz","üzüm"]},
  "77": {"ad":"Yalova","bolge":"Marmara","yapilar":["Çınarcık Plajı","Atatürk Arboretumu","Termal Kaplıca"],"urunler":["zeytin","üzüm","elma"]},
  "78": {"ad":"Karabük","bolge":"Karadeniz","yapilar":["Safranbolu","Karabük Kalesi","Kurucaşile Sahili"],"urunler":["ceviz","bal","zeytin"]},
  "79": {"ad":"Kilis","bolge":"Güneydoğu Anadolu","yapilar":["Kilis Kalesi","Mor Ezzi Camii","Koramaz Vadisi"],"urunler":["antepfıstığı","zeytin","nar"]},
  "80": {"ad":"Osmaniye","bolge":"Akdeniz","yapilar":["Haruniye Kaplıcaları","Yumurtalık Plajı","Toprakkale"],"urunler":["zeytin","narenciye","ceviz"]},
  "81": {"ad":"Düzce","bolge":"Karadeniz","yapilar":["Samandere Şelalesi","Güzeldere Şelalesi","Düzce Müzesi"],"urunler":["fındık","bal","elma"]}

}