# Generated by Django 4.2.7 on 2024-01-25 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zb_auth', '0009_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='app_profile',
            new_name='app_settings',
        ),
    ]
