# Generated by Django 5.1.7 on 2025-06-23 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_audit_log', '0009_logpath_exclude_path_loguseragent_exclude_agent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesslog',
            name='in_always_log_urls',
        ),
        migrations.RemoveField(
            model_name='accesslog',
            name='in_sample_urls',
        ),
    ]
