# coding: utf-8

"""
    AristaFlowREST/ProcessManager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import af_process_manager
from af_process_manager.models.double_ge import DoubleGe  # noqa: E501
from af_process_manager.rest import ApiException


class TestDoubleGe(unittest.TestCase):
    """DoubleGe unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDoubleGe(self):
        """Test DoubleGe"""
        # FIXME: construct object with mandatory attributes with example values
        # model = af_process_manager.models.double_ge.DoubleGe()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
