# coding: utf-8

"""
    AristaFlowREST/ProcessManager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import af_process_manager
from af_process_manager.models.and_integer_filter import AndIntegerFilter  # noqa: E501
from af_process_manager.rest import ApiException


class TestAndIntegerFilter(unittest.TestCase):
    """AndIntegerFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAndIntegerFilter(self):
        """Test AndIntegerFilter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = af_process_manager.models.and_integer_filter.AndIntegerFilter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
