# coding: utf-8

"""
    AristaFlowREST/ProcessManager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import af_process_manager
from af_process_manager.models.instant_le import InstantLe  # noqa: E501
from af_process_manager.rest import ApiException


class TestInstantLe(unittest.TestCase):
    """InstantLe unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstantLe(self):
        """Test InstantLe"""
        # FIXME: construct object with mandatory attributes with example values
        # model = af_process_manager.models.instant_le.InstantLe()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
