FLD_LAST_PRICE = 'PX_LAST'
TICKER_BBG_MSCI_KR = 'MXKR Index'
TICKER_BBG_MSCI_KR_USD = 'M1KR Index'
TICKER_BBG_SP500 = 'SPY US Equity'
TICKER_BBG_SP500_INVERSE = 'SU US Equity'
TICKER_BBG_USDKRW = 'USDKRW Curncy'
TICKERS_BBG_TEST = ['MXKR Index', 'M1KR Index', 'SPY US Equity', 'SU US Equity', 'USDKRW Curncy', 'CRCL US Equity']
