# coding: utf-8

"""
    AristaFlowREST/WorklistManager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 6.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import af_worklist_manager
from af_worklist_manager.models.all_qa_filter import AllQaFilter  # noqa: E501
from af_worklist_manager.rest import ApiException


class TestAllQaFilter(unittest.TestCase):
    """AllQaFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllQaFilter(self):
        """Test AllQaFilter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = af_worklist_manager.models.all_qa_filter.AllQaFilter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
