# coding: utf-8

"""
    AristaFlowREST/WorklistManager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 6.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import af_worklist_manager
from af_worklist_manager.models.activity_reference_filter import ActivityReferenceFilter  # noqa: E501
from af_worklist_manager.rest import ApiException


class TestActivityReferenceFilter(unittest.TestCase):
    """ActivityReferenceFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActivityReferenceFilter(self):
        """Test ActivityReferenceFilter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = af_worklist_manager.models.activity_reference_filter.ActivityReferenceFilter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
