# coding: utf-8

"""
    AristaFlowREST/WorklistManager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 6.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import af_worklist_manager
from af_worklist_manager.models.all_uri_filter import AllUriFilter  # noqa: E501
from af_worklist_manager.rest import ApiException


class TestAllUriFilter(unittest.TestCase):
    """AllUriFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllUriFilter(self):
        """Test AllUriFilter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = af_worklist_manager.models.all_uri_filter.AllUriFilter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
