# coding: utf-8

"""
    AristaFlowREST/WorklistManager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 6.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import af_worklist_manager
from af_worklist_manager.models.worklist_item_state_in import WorklistItemStateIn  # noqa: E501
from af_worklist_manager.rest import ApiException


class TestWorklistItemStateIn(unittest.TestCase):
    """WorklistItemStateIn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorklistItemStateIn(self):
        """Test WorklistItemStateIn"""
        # FIXME: construct object with mandatory attributes with example values
        # model = af_worklist_manager.models.worklist_item_state_in.WorklistItemStateIn()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
