from .clean import deploy_clean
from .code import deploy_code
from .end import deploy_end
from .env import deploy_env
from .lock import deploy_lock
from .release import deploy_release
from .setup import deploy_setup
from .shared import deploy_shared
from .start import deploy_start
from .symlink import deploy_symlink
from .unlock import deploy_unlock
from .writable import deploy_writable
