#  anonymizer_config.py


DEFAULT_PSEUDONYMS = {
    "Person": [
        "Frodo Baggins",
        "Harry Potter",
        "Jack Sparrow",
        "Dexter Morgan",
        "Honey Bonney",
        "Benjamin Button",
        "Marge Simpson",
        "Pepper Potts",
        "Holly Golightly",
        "Don Draper",
        "Forrest Gump",
        "Edna Krabappel",
        "James Bond",
        "Peregrin Took",
        "Sarah Connors",
        "Clarisse Cavendish",
        "Louella Warner",
        "Evelyn Cleveland",
        "Raphaela Donovan",
        "Delta Lombardi",
        "Sadie Mack",
        "Giulia Lawton",
        "Gracie Kilpatrick",
        "Noa Fontaine",
        "Mylah Barney",
        "Zinnia Christensen",
        "Andrea Oakes",
        "Charity Bouvier",
        "Tessa Grenville",
        "Mia Kendrick",
        "Vera Jacobsen",
        "Xara Willoughby",
        "Trixie Cassidy",
        "Evie Ashford",
        "Tia Lawson",
        "Conor Faust",
        "Oliver Senna",
        "Angel Gray",
        "Richard Croix",
        "Conor Silva",
        "Cyprian Baptiste",
        "Lenny Gabriel",
        "Truett Oakes",
        "Justin Lovell",
        "Natha  n Watson",
        "Sherwin Faulkner",
        "Osiris Twain",
        "Harper Campbell",
        "Laurence Koch",
        "Diarmaid Garrick",
        "Alvin Bexley",
        "Santos Marlow",
        "Hunt Merrick",
        "Scott Malone",
        "Brad Willis",
        "Margaux Leblanc",
        "Jules Renault",
        "Amandine Gauthier",
        "Théo Lambert",
        "Léa Perrin",
        "Hugo Durand",
        "Capucine Leroy",
        "Romain Mercier",
        "Océane Faure",
        "Valentin Lemoine",
        "Maëlys Dubois",
        "Bastien Roussel",
        "Clémence Caron",
        "Maxime Giraud",
        "Noémie Bertrand",
        "Quentin Lefevre",
        "Inès Martin",
        "Lucas Morel",
        "Chloé Bernard",
        "Adrien Simon",
    ],
    "Company": [
        "Acme Corporation",
        "Die Hard Corp",
        "Terminator Ltd",
        "Globex Corporation",
        "Soylent Corp",
        "Duff Beer",
        "Initech",
        "Stark Industries",
        "Ollivander's Wand Shop",
        "Predator Technologies",
        "Wayne Enterprises",
        "Cyberdyne Systems",
        "The New York Inquirer",
        "Umbrella Corporation",
        "Hooli",
        "Bubba Gump",
        "Vehement Capital Partners",
        "Massive Dynamic",
        "Oceanic Airlines",
        "Big Kahuna Burger",
        "Wonka Industries",
        "Mooby’s",
        "Heisler Beer",
        "Krusty Krab",
        "Sterling Cooper",
        "Good Burger",
        "Life Extension",
        "Brawndo",
        "Parallax Corporation",
        "Megadodo Publications",
        "Multi National United",
        "Crimson Permanent Assurance",
        "Spectacular Optical",
        "Adventureland",
        "Lunar Industries",
        "Career Transitions Corporation",
        "Buy N Large",
        "McDowell's",
        "Kiki's Delivery Service",
        "Oscorp",
        "Rekall",
        "Quick Stop",
        "Nakatomi Trading Co.",
        "Bushwood Country Club",
        "Prestige Worldwide",
        "Rare Exports, Inc.",
        "Monsters, Inc.",
        "Amusing Ventures",
        "Hilarious Inc.",
        "Laughable Enterprises",
        "Witty Solutions",
        "Jokester Corporation",
        "Humorous Enterprises",
        "Chuckle Co.",
        "Comical Innovations",
        "Giggles and Grins Inc.",
        "Silly Solutions",
        "Spacely Sprockets",
        "Tyrell Corporation",
        "Gringotts",
        "Wonka Industries",
        "Cyberdyne Systems",
    ],
    "Position": [
        "Shredded Cheese Authority",
        "Chief Visionary Officer",
        "Chief People Herder",
        "Wizard",
        "Chief Guru",
        "Ninja Thinker",
        "Road Warrior",
        "Digital Overlord",
        "Cat Behaviour Consultant",
        "Smarties Expert",
        "Space Lawyer",
        "Dark Web Coach",
        "Science Viking",
        "Penguinologist",
        "Rasputin Impersonator",
        "Minister of Silly Walks",
    ],
    "Country": [
        "Borduria",
        "Syldavia",
        "San Teodoros",
        "São Rico",
        "Arendelle",
        "Berzerkistan",
        "Wakanda",
        "Zamunda",
        "Freedonia",
        "Syldavia",
        "Sokovia",
        "Agrabah",
        "Ruritania",
        "Pianosa",
        "Borduria",
        "Nambutu",
        "Zubrowka",
        "Kumandra",
    ],
    "Organization": [
        "Combined Miniature Deterrent Force",
        "Galactic Alliance Security",
        "Brotherhood of the Ring",
        "Ministry of Magic",
        "Judean Liberation Front",
        "People's Revolutionary Front",
        "Highest Anti Terrorism Effort",
        "Democratic Order of Planets",
        "Global Liberation Army",
        "Office of Secret Intelligence",
    ],
    "City": [
        "National City",
        "Gotham City",
        "Sunnydale",
        "Bludhaven",
        "Basin City",
        "Riverdale",
        "Smallville",
        "Metropolis",
        "Springfield",
        "Castle Rock",
        "Emerald City",
        "Mayberry",
        "Seabrook",
        "Aberdale",
        "South Park",
        "Shangri-La",
        "Middlemarch",
        "Lankhmar",
        "Los Santos",
        "Liberty City",
        "Avalon",
        "Walmington-on-Sea",
        "Metropolis",
        "Raccoon City",
        "Duckburg",
        "Woodbury",
        "Atlantis",
    ],
}

DEFAULT_ANNOTATIONS = "Person,Company,Position,Country,City"
