# Generated by ariadne-codegen
# Source: ../../../graphql/operations/

from typing import List, Optional
from uuid import UUID

from pydantic import Field

from .base_model import BaseModel


class AddS3BucketAccessConfigurations(BaseModel):
    s_3_bucket_access_configurations: Optional[
        "AddS3BucketAccessConfigurationsS3BucketAccessConfigurations"
    ] = Field(alias="s3BucketAccessConfigurations")


class AddS3BucketAccessConfigurationsS3BucketAccessConfigurations(BaseModel):
    affected_rows: int = Field(alias="affectedRows")
    returning: List[
        "AddS3BucketAccessConfigurationsS3BucketAccessConfigurationsReturning"
    ]


class AddS3BucketAccessConfigurationsS3BucketAccessConfigurationsReturning(BaseModel):
    s_3_bucket_access_configuration_id: UUID = Field(
        alias="s3BucketAccessConfigurationId"
    )


AddS3BucketAccessConfigurations.model_rebuild()
AddS3BucketAccessConfigurationsS3BucketAccessConfigurations.model_rebuild()
