# Generated by ariadne-codegen
# Source: ../../../graphql/operations/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class AddS3OperationPermissions(BaseModel):
    added_operation_permissions: Optional[
        "AddS3OperationPermissionsAddedOperationPermissions"
    ] = Field(alias="addedOperationPermissions")


class AddS3OperationPermissionsAddedOperationPermissions(BaseModel):
    affected_rows: int = Field(alias="affectedRows")


AddS3OperationPermissions.model_rebuild()
