# Generated by ariadne-codegen
# Source: ../../../graphql/operations/

from typing import Optional
from uuid import UUID

from pydantic import Field

from .base_model import BaseModel


class CreateTable(BaseModel):
    insert_catalog_dataset_one: Optional["CreateTableInsertCatalogDatasetOne"] = Field(
        alias="insertCatalogDatasetOne"
    )
    insert_catalog_table_one: Optional["CreateTableInsertCatalogTableOne"] = Field(
        alias="insertCatalogTableOne"
    )


class CreateTableInsertCatalogDatasetOne(BaseModel):
    dataset_id: UUID = Field(alias="datasetId")


class CreateTableInsertCatalogTableOne(BaseModel):
    table_id: UUID = Field(alias="tableId")


CreateTable.model_rebuild()
