# Generated by ariadne-codegen
# Source: ../../../graphql/operations/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import S3BucketAccessConfigurationDetails


class GetS3BucketAccessConfigurationById(BaseModel):
    bucket_access_configuration: Optional[
        "GetS3BucketAccessConfigurationByIdBucketAccessConfiguration"
    ] = Field(alias="bucketAccessConfiguration")


class GetS3BucketAccessConfigurationByIdBucketAccessConfiguration(
    S3BucketAccessConfigurationDetails
):
    pass


GetS3BucketAccessConfigurationById.model_rebuild()
