from enum import Enum

class ProtoTypeEnum(Enum):
    MISSION_REQUEST=0
    MISSION_RESPONSE=1
    MAP_MISSION_METADATA=2
    DYNAMICS=3
    AGENT_STATE=4
    DYNAMIC_OBSTACLE_STATE=5
    DYNAMIC_OBSTACLE_RISK_STATE=6
    STATIC_OBSTACLE_STATE=7
    STATIC_OBSTACLE_RISK_STATE=8
    OBSTACLES_STATE=9
    OBSTACLES_RISK_STATE=10
    UNSAFE_SET_STATE=11
    AUTOMATON_OUTPUT=12
    MISSION_COMPLETE=13
    

