# Generated by ariadne-codegen
# Source: ../../../graphql/operations/

from typing import Optional
from uuid import UUID

from pydantic import Field

from .base_model import BaseModel


class CreateEphemeralCatalog(BaseModel):
    created_catalog: Optional["CreateEphemeralCatalogCreatedCatalog"] = Field(
        alias="createdCatalog"
    )


class CreateEphemeralCatalogCreatedCatalog(BaseModel):
    catalog_id: UUID = Field(alias="catalogId")


CreateEphemeralCatalog.model_rebuild()
