# Generated by ariadne-codegen
# Source: ../../../graphql/operations/

from typing import Optional
from uuid import UUID

from pydantic import Field

from .base_model import BaseModel


class DropNamespace(BaseModel):
    delete_catalog_dataset: Optional["DropNamespaceDeleteCatalogDataset"] = Field(
        alias="deleteCatalogDataset"
    )
    delete_catalog_namespace_property: Optional[
        "DropNamespaceDeleteCatalogNamespaceProperty"
    ] = Field(alias="deleteCatalogNamespaceProperty")
    delete_catalog_namespace_by_pk: Optional[
        "DropNamespaceDeleteCatalogNamespaceByPk"
    ] = Field(alias="deleteCatalogNamespaceByPk")


class DropNamespaceDeleteCatalogDataset(BaseModel):
    affected_rows: int = Field(alias="affectedRows")


class DropNamespaceDeleteCatalogNamespaceProperty(BaseModel):
    affected_rows: int = Field(alias="affectedRows")


class DropNamespaceDeleteCatalogNamespaceByPk(BaseModel):
    namespace_id: UUID = Field(alias="namespaceId")
    name: str


DropNamespace.model_rebuild()
