# Generated by ariadne-codegen
# Source: ../../../graphql/operations/

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .fragments import ExecutionDetails


class ListQueryExecutionDetailsBySessionIdAndStatus(BaseModel):
    typedef_query_execution: List[
        "ListQueryExecutionDetailsBySessionIdAndStatusTypedefQueryExecution"
    ] = Field(alias="typedefQueryExecution")


class ListQueryExecutionDetailsBySessionIdAndStatusTypedefQueryExecution(
    ExecutionDetails
):
    pass


ListQueryExecutionDetailsBySessionIdAndStatus.model_rebuild()
