# Generated by ariadne-codegen
# Source: ../../../graphql/operations/

from datetime import datetime
from typing import Optional
from uuid import UUID

from pydantic import Field

from .base_model import BaseModel
from .enums import TypedefObjectStateReferenceEnum


class MarkCatalogAsDeleted(BaseModel):
    deleted_catalog: Optional["MarkCatalogAsDeletedDeletedCatalog"] = Field(
        alias="deletedCatalog"
    )


class MarkCatalogAsDeletedDeletedCatalog(BaseModel):
    catalog_id: UUID = Field(alias="catalogId")
    deleted_at: Optional[datetime] = Field(alias="deletedAt")
    object_state: Optional[TypedefObjectStateReferenceEnum] = Field(alias="objectState")


MarkCatalogAsDeleted.model_rebuild()
