
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-06-24T11:04:32+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "46c2341072820cc1cebe6f77fe754ed63a703988",
 "version": "2.31.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
