# coding: utf-8

"""
    AristaFlowREST/LicenceManager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import af_licence_manager
from af_licence_manager.models.ilm_stack_trace_element import IlmStackTraceElement  # noqa: E501
from af_licence_manager.rest import ApiException


class TestIlmStackTraceElement(unittest.TestCase):
    """IlmStackTraceElement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIlmStackTraceElement(self):
        """Test IlmStackTraceElement"""
        # FIXME: construct object with mandatory attributes with example values
        # model = af_licence_manager.models.ilm_stack_trace_element.IlmStackTraceElement()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
