# ruff: noqa: E501
# fmt: off
from servequery.legacy.features.generated_features import GeneratedFeatures
from servequery.pydantic_utils import register_type_alias

register_type_alias(GeneratedFeatures, "servequery.legacy.features.BERTScore_feature.BERTScoreFeature", "servequery:feature:BERTScoreFeature")
register_type_alias(GeneratedFeatures, "servequery.legacy.features.OOV_words_percentage_feature.OOVWordsPercentage", "servequery:feature:OOVWordsPercentage")
register_type_alias(GeneratedFeatures, "servequery.legacy.features.contains_link_feature.ContainsLink", "servequery:feature:ContainsLink")
register_type_alias(GeneratedFeatures, "servequery.legacy.features.custom_feature.CustomFeature", "servequery:feature:CustomFeature")
register_type_alias(GeneratedFeatures, "servequery.legacy.features.custom_feature.CustomPairColumnFeature", "servequery:feature:CustomPairColumnFeature")
register_type_alias(GeneratedFeatures, "servequery.legacy.features.custom_feature.CustomSingleColumnFeature", "servequery:feature:CustomSingleColumnFeature")
register_type_alias(GeneratedFeatures, "servequery.legacy.features.exact_match_feature.ExactMatchFeature", "servequery:feature:ExactMatchFeature")
register_type_alias(GeneratedFeatures, "servequery.legacy.features.hf_feature.HuggingFaceFeature", "servequery:feature:HuggingFaceFeature")
register_type_alias(GeneratedFeatures, "servequery.legacy.features.hf_feature.HuggingFaceToxicityFeature", "servequery:feature:HuggingFaceToxicityFeature")
register_type_alias(GeneratedFeatures, "servequery.legacy.features.is_valid_json_feature.IsValidJSON", "servequery:feature:IsValidJSON")
register_type_alias(GeneratedFeatures, "servequery.legacy.features.is_valid_python_feature.IsValidPython", "servequery:feature:IsValidPython")
register_type_alias(GeneratedFeatures, "servequery.legacy.features.is_valid_sql_feature.IsValidSQL", "servequery:feature:IsValidSQL")
register_type_alias(GeneratedFeatures, "servequery.legacy.features.json_match_feature.JSONMatch", "servequery:feature:JSONMatch")
register_type_alias(GeneratedFeatures, "servequery.legacy.features.json_schema_match_feature.JSONSchemaMatch", "servequery:feature:JSONSchemaMatch")
register_type_alias(GeneratedFeatures, "servequery.legacy.features.llm_judge.LLMJudge", "servequery:feature:LLMJudge")
register_type_alias(GeneratedFeatures, "servequery.legacy.features.non_letter_character_percentage_feature.NonLetterCharacterPercentage", "servequery:feature:NonLetterCharacterPercentage")
register_type_alias(GeneratedFeatures, "servequery.legacy.features.openai_feature.OpenAIFeature", "servequery:feature:OpenAIFeature")
register_type_alias(GeneratedFeatures, "servequery.legacy.features.regexp_feature.RegExp", "servequery:feature:RegExp")
register_type_alias(GeneratedFeatures, "servequery.legacy.features.semantic_similarity_feature.SemanticSimilarityFeature", "servequery:feature:SemanticSimilarityFeature")
register_type_alias(GeneratedFeatures, "servequery.legacy.features.sentence_count_feature.SentenceCount", "servequery:feature:SentenceCount")
register_type_alias(GeneratedFeatures, "servequery.legacy.features.sentiment_feature.Sentiment", "servequery:feature:Sentiment")
register_type_alias(GeneratedFeatures, "servequery.legacy.features.text_contains_feature.Contains", "servequery:feature:Contains")
register_type_alias(GeneratedFeatures, "servequery.legacy.features.text_contains_feature.DoesNotContain", "servequery:feature:DoesNotContain")
register_type_alias(GeneratedFeatures, "servequery.legacy.features.text_contains_feature.ItemMatch", "servequery:feature:ItemMatch")
register_type_alias(GeneratedFeatures, "servequery.legacy.features.text_contains_feature.ItemNoMatch", "servequery:feature:ItemNoMatch")
register_type_alias(GeneratedFeatures, "servequery.legacy.features.text_length_feature.TextLength", "servequery:feature:TextLength")
register_type_alias(GeneratedFeatures, "servequery.legacy.features.text_part_feature.BeginsWith", "servequery:feature:BeginsWith")
register_type_alias(GeneratedFeatures, "servequery.legacy.features.text_part_feature.EndsWith", "servequery:feature:EndsWith")
register_type_alias(GeneratedFeatures, "servequery.legacy.features.trigger_words_presence_feature.TriggerWordsPresent", "servequery:feature:TriggerWordsPresent")
register_type_alias(GeneratedFeatures, "servequery.legacy.features.word_count_feature.WordCount", "servequery:feature:WordCount")
register_type_alias(GeneratedFeatures, "servequery.legacy.features.words_feature.ExcludesWords", "servequery:feature:ExcludesWords")
register_type_alias(GeneratedFeatures, "servequery.legacy.features.words_feature.IncludesWords", "servequery:feature:IncludesWords")
register_type_alias(GeneratedFeatures, "servequery.legacy.features.words_feature.RowWordPresence", "servequery:feature:RowWordPresence")
register_type_alias(GeneratedFeatures, "servequery.legacy.features.words_feature.WordMatch", "servequery:feature:WordMatch")
register_type_alias(GeneratedFeatures, "servequery.legacy.features.words_feature.WordNoMatch", "servequery:feature:WordNoMatch")
register_type_alias(GeneratedFeatures, "servequery.legacy.features.words_feature.WordsPresence", "servequery:feature:WordsPresence")
