
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-06-21T09:54:48-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3161250c0b4c97a8d74a34744912be0e113cd364",
 "version": "2025.6.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
