
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-06-24T16:58:58-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e47f4cd1e5eff24965e7fe34db7d2b7e9ff0a04e",
 "version": "1.3.0-alpha"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
