from .absence import AbsenceSchema
from .absence_group import AbsenceGroupSchema
from .absence_type import AbsenceTypeSchema
from .classification import ClassificationSchema
from .compensation_and_benefit import CompensationAndBenefitSchema
from .content_type import ContentTypeSchema
from .course import CourseSchema
from .course_calendar import CourseCalendarSchema
from .course_supplier import CourseSupplierSchema
from .customer import CustomerSchema
from .employee import EmployeeSchema
from .employee_qualification import EmployeeQualificationSchema
from .employer import EmployerSchema
from .employment import EmploymentSchema
from .employment_classification import EmploymentClassificationSchema
from .organization import OrganizationSchema
from .organizational_unit import OrganizationalUnitSchema
from .pay_type import PayTypeSchema
from .payment_condition_classification import PaymentConditionClassificationSchema
from .payroll import PayrollSchema
from .phone_number import PhoneNumberSchema
from .posted_accounting import PostedAccountingSchema
from .processed_absence import ProcessedAbsenceSchema
from .processed_absence_group import ProcessedAbsenceGroupSchema
from .salary import SalarySchema
from .salary_comment import SalaryCommentSchema
from .tax_card import TaxCardSchema
from .visma_loen_work_calendar import VismaLoenWorkCalendarSchema 