# coding: utf-8

"""
    Jellyfin API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 10.11.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.artists_api import ArtistsApi


class TestArtistsApi(unittest.TestCase):
    """ArtistsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ArtistsApi()

    def tearDown(self) -> None:
        pass

    def test_get_album_artists(self) -> None:
        """Test case for get_album_artists

        Gets all album artists from a given item, folder, or the entire library.
        """
        pass

    def test_get_artist_by_name(self) -> None:
        """Test case for get_artist_by_name

        Gets an artist by name.
        """
        pass

    def test_get_artists(self) -> None:
        """Test case for get_artists

        Gets all artists from a given item, folder, or the entire library.
        """
        pass


if __name__ == '__main__':
    unittest.main()
