# coding: utf-8

"""
    Jellyfin API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 10.11.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.api_key_api import ApiKeyApi


class TestApiKeyApi(unittest.TestCase):
    """ApiKeyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApiKeyApi()

    def tearDown(self) -> None:
        pass

    def test_create_key(self) -> None:
        """Test case for create_key

        Create a new api key.
        """
        pass

    def test_get_keys(self) -> None:
        """Test case for get_keys

        Get all keys.
        """
        pass

    def test_revoke_key(self) -> None:
        """Test case for revoke_key

        Remove an api key.
        """
        pass


if __name__ == '__main__':
    unittest.main()
