# coding: utf-8

"""
    Jellyfin API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 10.11.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.library_structure_api import LibraryStructureApi


class TestLibraryStructureApi(unittest.TestCase):
    """LibraryStructureApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LibraryStructureApi()

    def tearDown(self) -> None:
        pass

    def test_add_media_path(self) -> None:
        """Test case for add_media_path

        Add a media path to a library.
        """
        pass

    def test_add_virtual_folder(self) -> None:
        """Test case for add_virtual_folder

        Adds a virtual folder.
        """
        pass

    def test_get_virtual_folders(self) -> None:
        """Test case for get_virtual_folders

        Gets all virtual folders.
        """
        pass

    def test_remove_media_path(self) -> None:
        """Test case for remove_media_path

        Remove a media path.
        """
        pass

    def test_remove_virtual_folder(self) -> None:
        """Test case for remove_virtual_folder

        Removes a virtual folder.
        """
        pass

    def test_rename_virtual_folder(self) -> None:
        """Test case for rename_virtual_folder

        Renames a virtual folder.
        """
        pass

    def test_update_library_options(self) -> None:
        """Test case for update_library_options

        Update library options.
        """
        pass

    def test_update_media_path(self) -> None:
        """Test case for update_media_path

        Updates a media path.
        """
        pass


if __name__ == '__main__':
    unittest.main()
