# coding: utf-8

"""
    Jellyfin API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 10.11.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.metadata_editor_info import MetadataEditorInfo

class TestMetadataEditorInfo(unittest.TestCase):
    """MetadataEditorInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MetadataEditorInfo:
        """Test MetadataEditorInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MetadataEditorInfo`
        """
        model = MetadataEditorInfo()
        if include_optional:
            return MetadataEditorInfo(
                parental_rating_options = [
                    openapi_client.models.parental_rating.ParentalRating(
                        name = '', 
                        value = 56, 
                        rating_score = null, )
                    ],
                countries = [
                    openapi_client.models.country_info.CountryInfo(
                        name = '', 
                        display_name = '', 
                        two_letter_iso_region_name = '', 
                        three_letter_iso_region_name = '', )
                    ],
                cultures = [
                    openapi_client.models.culture_dto.CultureDto(
                        name = '', 
                        display_name = '', 
                        two_letter_iso_language_name = '', 
                        three_letter_iso_language_name = '', 
                        three_letter_iso_language_names = [
                            ''
                            ], )
                    ],
                external_id_infos = [
                    openapi_client.models.external_id_info.ExternalIdInfo(
                        name = '', 
                        key = '', 
                        type = 'Album', )
                    ],
                content_type = 'unknown',
                content_type_options = [
                    openapi_client.models.name_value_pair.NameValuePair(
                        name = '', 
                        value = '', )
                    ]
            )
        else:
            return MetadataEditorInfo(
        )
        """

    def testMetadataEditorInfo(self):
        """Test MetadataEditorInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
