# coding: utf-8

"""
    Jellyfin API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 10.11.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.image_info import ImageInfo

class TestImageInfo(unittest.TestCase):
    """ImageInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImageInfo:
        """Test ImageInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImageInfo`
        """
        model = ImageInfo()
        if include_optional:
            return ImageInfo(
                image_type = 'Primary',
                image_index = 56,
                image_tag = '',
                path = '',
                blur_hash = '',
                height = 56,
                width = 56,
                size = 56
            )
        else:
            return ImageInfo(
        )
        """

    def testImageInfo(self):
        """Test ImageInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
