# coding: utf-8

"""
    Jellyfin API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 10.11.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.buffer_request_dto import BufferRequestDto

class TestBufferRequestDto(unittest.TestCase):
    """BufferRequestDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BufferRequestDto:
        """Test BufferRequestDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BufferRequestDto`
        """
        model = BufferRequestDto()
        if include_optional:
            return BufferRequestDto(
                when = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                position_ticks = 56,
                is_playing = True,
                playlist_item_id = ''
            )
        else:
            return BufferRequestDto(
        )
        """

    def testBufferRequestDto(self):
        """Test BufferRequestDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
