# coding: utf-8

"""
    Jellyfin API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 10.11.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.transcode_reason import TranscodeReason

class TestTranscodeReason(unittest.TestCase):
    """TranscodeReason unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTranscodeReason(self):
        """Test TranscodeReason"""
        # inst = TranscodeReason()

if __name__ == '__main__':
    unittest.main()
