# coding: utf-8

"""
    Jellyfin API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 10.11.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.collection_type_options import CollectionTypeOptions

class TestCollectionTypeOptions(unittest.TestCase):
    """CollectionTypeOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCollectionTypeOptions(self):
        """Test CollectionTypeOptions"""
        # inst = CollectionTypeOptions()

if __name__ == '__main__':
    unittest.main()
