# coding: utf-8

"""
    Jellyfin API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 10.11.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.trickplay_api import TrickplayApi


class TestTrickplayApi(unittest.TestCase):
    """TrickplayApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TrickplayApi()

    def tearDown(self) -> None:
        pass

    def test_get_trickplay_hls_playlist(self) -> None:
        """Test case for get_trickplay_hls_playlist

        Gets an image tiles playlist for trickplay.
        """
        pass

    def test_get_trickplay_tile_image(self) -> None:
        """Test case for get_trickplay_tile_image

        Gets a trickplay tile image.
        """
        pass


if __name__ == '__main__':
    unittest.main()
