# coding: utf-8

"""
    Jellyfin API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 10.11.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.remove_from_playlist_request_dto import RemoveFromPlaylistRequestDto

class TestRemoveFromPlaylistRequestDto(unittest.TestCase):
    """RemoveFromPlaylistRequestDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RemoveFromPlaylistRequestDto:
        """Test RemoveFromPlaylistRequestDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RemoveFromPlaylistRequestDto`
        """
        model = RemoveFromPlaylistRequestDto()
        if include_optional:
            return RemoveFromPlaylistRequestDto(
                playlist_item_ids = [
                    ''
                    ],
                clear_playlist = True,
                clear_playing_item = True
            )
        else:
            return RemoveFromPlaylistRequestDto(
        )
        """

    def testRemoveFromPlaylistRequestDto(self):
        """Test RemoveFromPlaylistRequestDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
