# coding: utf-8

"""
    Jellyfin API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 10.11.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.display_preferences_api import DisplayPreferencesApi


class TestDisplayPreferencesApi(unittest.TestCase):
    """DisplayPreferencesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DisplayPreferencesApi()

    def tearDown(self) -> None:
        pass

    def test_get_display_preferences(self) -> None:
        """Test case for get_display_preferences

        Get Display Preferences.
        """
        pass

    def test_update_display_preferences(self) -> None:
        """Test case for update_display_preferences

        Update Display Preferences.
        """
        pass


if __name__ == '__main__':
    unittest.main()
