# coding: utf-8

"""
    Jellyfin API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 10.11.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.localization_api import LocalizationApi


class TestLocalizationApi(unittest.TestCase):
    """LocalizationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LocalizationApi()

    def tearDown(self) -> None:
        pass

    def test_get_countries(self) -> None:
        """Test case for get_countries

        Gets known countries.
        """
        pass

    def test_get_cultures(self) -> None:
        """Test case for get_cultures

        Gets known cultures.
        """
        pass

    def test_get_localization_options(self) -> None:
        """Test case for get_localization_options

        Gets localization options.
        """
        pass

    def test_get_parental_ratings(self) -> None:
        """Test case for get_parental_ratings

        Gets known parental ratings.
        """
        pass


if __name__ == '__main__':
    unittest.main()
