# coding: utf-8

"""
    Jellyfin API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 10.11.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.media_info_api import MediaInfoApi


class TestMediaInfoApi(unittest.TestCase):
    """MediaInfoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MediaInfoApi()

    def tearDown(self) -> None:
        pass

    def test_close_live_stream(self) -> None:
        """Test case for close_live_stream

        Closes a media source.
        """
        pass

    def test_get_bitrate_test_bytes(self) -> None:
        """Test case for get_bitrate_test_bytes

        Tests the network with a request with the size of the bitrate.
        """
        pass

    def test_get_playback_info(self) -> None:
        """Test case for get_playback_info

        Gets live playback media info for an item.
        """
        pass

    def test_get_posted_playback_info(self) -> None:
        """Test case for get_posted_playback_info

        Gets live playback media info for an item.
        """
        pass

    def test_open_live_stream(self) -> None:
        """Test case for open_live_stream

        Opens a media source.
        """
        pass


if __name__ == '__main__':
    unittest.main()
