# coding: utf-8

"""
    Jellyfin API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 10.11.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.group_shuffle_mode import GroupShuffleMode

class TestGroupShuffleMode(unittest.TestCase):
    """GroupShuffleMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGroupShuffleMode(self):
        """Test GroupShuffleMode"""
        # inst = GroupShuffleMode()

if __name__ == '__main__':
    unittest.main()
