# coding: utf-8

"""
    Jellyfin API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 10.11.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.trickplay_info import TrickplayInfo

class TestTrickplayInfo(unittest.TestCase):
    """TrickplayInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TrickplayInfo:
        """Test TrickplayInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TrickplayInfo`
        """
        model = TrickplayInfo()
        if include_optional:
            return TrickplayInfo(
                item_id = '',
                width = 56,
                height = 56,
                tile_width = 56,
                tile_height = 56,
                thumbnail_count = 56,
                interval = 56,
                bandwidth = 56
            )
        else:
            return TrickplayInfo(
        )
        """

    def testTrickplayInfo(self):
        """Test TrickplayInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
