# coding: utf-8

"""
    Jellyfin API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 10.11.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.scheduled_tasks_info_message import ScheduledTasksInfoMessage

class TestScheduledTasksInfoMessage(unittest.TestCase):
    """ScheduledTasksInfoMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScheduledTasksInfoMessage:
        """Test ScheduledTasksInfoMessage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScheduledTasksInfoMessage`
        """
        model = ScheduledTasksInfoMessage()
        if include_optional:
            return ScheduledTasksInfoMessage(
                data = [
                    openapi_client.models.task_info.TaskInfo(
                        name = '', 
                        state = 'Idle', 
                        current_progress_percentage = 1.337, 
                        id = '', 
                        last_execution_result = null, 
                        triggers = [
                            openapi_client.models.task_trigger_info.TaskTriggerInfo(
                                type = 'DailyTrigger', 
                                time_of_day_ticks = 56, 
                                interval_ticks = 56, 
                                day_of_week = 'Sunday', 
                                max_runtime_ticks = 56, )
                            ], 
                        description = '', 
                        category = '', 
                        is_hidden = True, 
                        key = '', )
                    ],
                message_id = '',
                message_type = 'ForceKeepAlive'
            )
        else:
            return ScheduledTasksInfoMessage(
        )
        """

    def testScheduledTasksInfoMessage(self):
        """Test ScheduledTasksInfoMessage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
