# Generated by Django 4.2 on 2025-05-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_async_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["queue"], name="django_asyn_queue_de1c17_idx"),
        ),
    ]
