# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Dockerfile for Laravel Docs MCP Server
FROM python:3.12-alpine

# Install build dependencies (if necessary)
RUN apk add --no-cache build-base libffi-dev openssl-dev

# Set working directory
WORKDIR /app

# Copy project files
COPY . .

# Install Python dependencies
RUN pip install --no-cache-dir fastmcp mcp[cli,client]

# Default environment
ENV PYTHONUNBUFFERED=1

# Expose port for HTTP transport
EXPOSE 8000

# Run the MCP server with HTTP transport
CMD ["python", "laravel_docs_server.py", "--transport", "sse", "--host", "0.0.0.0", "--port", "8000"]
