# coding: utf-8

"""
    AristaFlowREST/OrgModelManager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 5.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import af_org_model_manager
from af_org_model_manager.api.entity_remote_iterator_api import EntityRemoteIteratorApi  # noqa: E501
from af_org_model_manager.rest import ApiException


class TestEntityRemoteIteratorApi(unittest.TestCase):
    """EntityRemoteIteratorApi unit test stubs"""

    def setUp(self):
        self.api = EntityRemoteIteratorApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ent_close(self):
        """Test case for ent_close

        """
        pass

    def test_ent_get_next(self):
        """Test case for ent_get_next

        """
        pass

    def test_ent_get_previous(self):
        """Test case for ent_get_previous

        """
        pass

    def test_ent_keep_alive(self):
        """Test case for ent_keep_alive

        """
        pass


if __name__ == '__main__':
    unittest.main()
